### ISSUE TITLE
Panic when retrying MultiWrite with the same regv1.Update channel

### ISSUE THREAD

**Issue by DennisDenuto** [google/go-containerregistry#1038]
# Description

We have been enjoying having the ability to display a progress bar using the `regv1.Update` channel in `MultiWrite` and `Write`

However, we have run into a panic when 'retrying' a `MultiWrite` using the same `regv1.Update` channel. (Because the 'writer' has already closed the channel)

The simple solution would be to not use the same channel when 'retrying' a `Write`. However due to abstractions that we have in place (a registry struct that holds state necessary to make a series of go-containerregistry calls with opts) this becomes tricky.

# Use case
1X reader of the channel
1X writer of the channel, invoked multiple times in a retry loop

```
util.Retry(func() error {
	return regremote.MultiWrite(imageOrIndexesToUpload, r.opts)
})
```

# Suggestions:
Writer *never* closes the channel, instead the onus is on the 'reader' of the channel / creator of the channel. 
or
Provide an option to toggle whether the 'reader' or 'writer' closes the channel

**Comment by imjasonh** [comment]
I think it's a bit cleaner to have the method close the channel, it lets you do something like:

```
ch := make(chan v1.Update)
go remote.MultiWrite(..., remote.WithProgress(ch))
for u := range ch {
  fmt.Println(u)
}
```

If the caller was responsible for closing it'd only be possible to consume updates in a goroutine and close it yourself manually.

If retries is what you're after, we already bake retries into MultiWrite (I think...), and could expose an Option to configure that differently.

Out of curiosity, what failures are you seeing that MultiWrite's retries aren't successfully hiding from you?

**Comment by jonjohnsonjr** [comment]
Seems like it would be better if we weren't dealing with channels directly but some different api/interface.

**Comment by DennisDenuto** [comment]
Thanks for the replies!

> Out of curiosity, what failures are you seeing that MultiWrite's retries aren't successfully hiding from you?

From what we can tell, MultiWrite doesn't retry during a `commitManifest`. Same goes with other functions (i.e. WriteTag)

We want to retry on *every* http request to a registry (except on certain http errors such as auth related). 

> could expose an Option to configure that differently

That would be nice, and hopefully remove our need to retry around ggcr functions. And if *that* was true, having the writer close the channel would be a non-issue for us at least.

 > If the caller was responsible for closing it'd only be possible to consume updates in a goroutine and close it yourself manually.

Yeah, that matches our structure. We have our 'ui' layer running in a go routine consuming updates to print to the terminal. And our main thread runs the main workflow of doing image stuff to registries, sending updates to the 'ui' thread via channel.
```
ch := make(chan v1.Update)
// defer close(ch) <- channel creator would be responsible for closing if MultiWrite doesn't close the channel.

go func() {
  for u := range ch {
    fmt.Println(u)
  }
}()

util.Retry(
  remote.MultiWrite(..., remote.WithProgress(ch))
)

```


> Seems like it would be better if we weren't dealing with channels directly but some different api/interface.

Sounds interesting. A callback function comes to top of mind reading that. Did you have any specific ideas?

**Comment by jonjohnsonjr** [comment]
> From what we can tell, MultiWrite doesn't retry during a commitManifest. Same goes with other functions (i.e. WriteTag)

This seems like something we could fix -- what kind of errors are you seeing?

> Did you have any specific ideas?

Tempted to borrow this from docker: https://github.com/moby/moby/blob/e0cabedf14d0eac1e9a41036c7df9745cc0adfa1/pkg/progress/progress.go#L36

**Comment by imjasonh** [comment]
lol

https://github.com/moby/moby/blob/e0cabedf14d0eac1e9a41036c7df9745cc0adfa1/pkg/progress/progress.go#L42-L45

**Comment by DennisDenuto** [comment]
> This seems like something we could fix -- what kind of errors are you seeing?

Great, and I am happy to help submit a PR to add additional retry logic around Write/MultiWrite at least. I was thinking any place where a network call is made in MultiWrite, retry similar to what `uploadOne` does. Currently retry it hardcoded to 3. Perhaps making that configurable too?

The kind of errors our users have run into are classified as 'network flakiness'. We haven't really debugged further since retrying seems to work great! :-)

**Comment by jonjohnsonjr** [comment]
So there are two interesting places that retries currently happen:

We have a [retrying transport](https://github.com/google/go-containerregistry/blob/b69114f97fced290a3dbe8b4104c697ac8b463c2/pkg/v1/remote/transport/retry.go#L64) that tries to smooth over various networking flakes, [wired up here](https://github.com/google/go-containerregistry/blob/b69114f97fced290a3dbe8b4104c697ac8b463c2/pkg/v1/remote/options.go#L81).

However, some things can't be retried at a request level. E.g. if you need to re-read a a layer from the network or the filesystem, we'd need to call `Compressed()` again, which is why we have that code in [`uploadOne`](https://github.com/google/go-containerregistry/blob/b69114f97fced290a3dbe8b4104c697ac8b463c2/pkg/v1/remote/write.go#L440-L448).

I added some more errors in https://github.com/google/go-containerregistry/pull/1019 which we probably want to retry for some other requests, but not all of them.

I'm wary of accidentally multiplying the number of retries we have (i.e., I don't want to have a blanket retry at the top of the Write functions), but I think adding them to `commitManifest` seems fine to me.

> Currently retry is hardcoded to 3 attempts. Perhaps making that configurable too?

Given above, I'm not sure how to make this make sense. I don't want you to have to think about retries in multiple places, but setting them all to the same value seems odd. Having a single retry might be a better default for these higher level operations?

**Comment by DennisDenuto** [comment]
Thank you for the detailed response.

Ahh cool [retrying transport](https://github.com/google/go-containerregistry/blob/b69114f97fced290a3dbe8b4104c697ac8b463c2/pkg/v1/remote/transport/retry.go#L64). I didn't notice that detail.

So the retrying transport should handle 'low level network flakiness' where a http response was not received. That leaves (for us) errors that *did* get a http response, however we would like to retry (i.e. http 503)

Sounds like y'all are ok with me adding a retry to `commitManifest` (similar to uploadOne).

Specifically, I am trying to make the following 'hacked together' test green: https://github.com/DennisDenuto/go-containerregistry/commit/4954e4ad76d0844bb6e2b41105a1b221344c3bf0

> Having a single retry might be a better default for these higher level operations?

Can you elaborate on this. I'm not quite following...

**Comment by jonjohnsonjr** [comment]
> Can you elaborate on this. I'm not quite following...

Mostly thinking about this as a heuristic rather than introducing too much configuration.

For things where maybe you just lost network connectivity for some amount of time, it makes sense to me to retry a handful of times, but something like a 5xx response from the server usually means that the server is experiencing some kind of outage (and retrying might be harmful to it) or there was some rare failure mode that got hit (maybe a rollout that isn't super graceful).

Retrying the network vs retrying the server feel like they should have different heuristics. I would expect most of the time a single retry to resolve a 5xx issue, but if your wifi is spotty, you might need to continually retry for the network.

Does that make sense?

**Comment by jonjohnsonjr** [comment]
Another thing I forgot to mention that might not be obvious is this: https://github.com/google/go-containerregistry/blob/b69114f97fced290a3dbe8b4104c697ac8b463c2/pkg/v1/remote/transport/error.go#L89-L101

The transport returns structured errors,  some of which are temporary. There are some places where that might be useful.

> Sounds like y'all are ok with me adding a retry to commitManifest (similar to uploadOne).

Yep, this sounds reasonable to me. I'm less excited about adding configuration for the retry mechanism, but we can discuss it if you think it's necessary.

**Comment by DennisDenuto** [comment]
Ah right yeah that makes sense.

I've quickly put together a POC commit to introduce retrying the commitManifest function https://github.com/DennisDenuto/go-containerregistry/commit/b8e552782666575041fcb7bd67f9df25a3c01ef7

Still wanna add some tests to make sure that no regressions are introduced with the progress channel, and general tidying. 

> less excited about adding configuration for the retry mechanism

Leaving the http server retries set to 3 in both places would be ok.  It would provide enough confidence that our users would not start experiencing failures that were 'hidden' by us setting the retry of the entire MultiWrite to 5 times (which technically could result in a lot more retries than 5 times).

**Comment by imjasonh** [comment]
Thanks for this fix @DennisDenuto !
