### ISSUE TITLE
Support eStargz in remoteImageLayer

### ISSUE THREAD

**Issue by knqyf263** [google/go-containerregistry#1050]
It would be great if go-containerregistry supports eStargz in remoteImageLayer. It allows a client to pull only necessary files from a layer without pulling the entire layer.
https://github.com/containerd/stargz-snapshotter/blob/master/docs/stargz-estargz.md

I think we have to add some methods like `Footer()`, `TOC()`, `OpenFile(filepath string)`, and eStargz specific methods. But it is not compatible with v1.Layer. I'd like to discuss how to support it in go-containerregistry.

**Comment by jonjohnsonjr** [comment]
Somewhat related:

https://github.com/google/go-containerregistry/issues/487
https://github.com/google/go-containerregistry/issues/921
https://github.com/google/go-containerregistry/issues/1011

My first impression is that we should implement the interfaces from the `io/fs` package, and take advantage of stargz information to make that more efficient, rather than directly exposing the stargz information.

I think [`ReadDirFS`](https://tip.golang.org/pkg/io/fs/#ReadDirFS) satisfies a lot of this. [`GlobFS`](https://tip.golang.org/pkg/io/fs/#GlobFS) could be similar to `TOC()`.

Does that make sense? Do you have any use cases in mind where you actually want the specific stargz info? We could do both, but everything I have in mind would be satisfied by the `io/fs` interfaces, I think.

**Comment by knqyf263** [comment]
Yes, [fs.WalkDir](https://tip.golang.org/pkg/io/fs/#WalkDir) satisfies my case.
