### ISSUE TITLE
crane append to /var/run/docker.sock

### ISSUE THREAD

**Issue by johnpoth** [google/go-containerregistry#1055]
Hi all, great project!

I trying out `crane` to do something like 

`crane append -f foo.zip  -t foobar` but getting

```
2021/06/16 19:44:40 base unspecified, using empty image
2021/06/16 19:44:40 No matching credentials were found, falling back on anonymous
2021/06/16 19:44:42 pushing image foobar: HEAD https://index.docker.io/v2/library/foobar/blobs/sha256:a0190f023ef9d3c0fea1770ea93de69fdc6222bca2d64d9f12895f3be8756aa5: unsupported status code 401
```

I am guessing this isn't possible to push to a local Docker setup (no http registry) via /var/run/docker.sock ?

Thanks !

**Comment by jonjohnsonjr** [comment]
Yeah this isn't currently possible, and I don't think I want to make it possible directly.

It's easy enough to do with the library via the [`daemon`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/daemon) package, but I've done my best to avoid linking that into the `crane` CLI because it causes a big dependency graph headache elsewhere.

Primarily, `crane` is for interacting with registries, and I've struggled with how we can cleanly extend this to other formats: https://github.com/google/go-containerregistry/pull/896#issuecomment-769359106

I haven't come up with an obviously good solution there...

On the other hand, I _have_ considered extended our (very basic, in-memory only) [registry implementation](https://github.com/google/go-containerregistry/blob/main/cmd/registry/main.go), which is currently just used for testing, and making that a little more useful for cases like yours where you don't really want to run a full registry, but having a local registry would be useful.

**Comment by johnpoth** [comment]
thanks for the info! I'll just whip up a HTTP Docker registry it's fine. I think we can close this issue. 

This project has an awesome abstraction of the Docker images and layers, is there any doc on this or is the code the best place to get a better idea of what's going on ? Thanks !

**Comment by jonjohnsonjr** [comment]
> thanks for the info! I'll just whip up a HTTP Docker registry it's fine. I think we can close this issue.

Sounds good! Sorry it's not easier :) 

>  This project has an awesome abstraction of the Docker images and layers, is there any doc on this or is the code the best place to get a better idea of what's going on ? Thanks !

Thank you!

The closest thing to that kind of doc is probably here: https://github.com/google/go-containerregistry/blob/main/pkg/v1/mutate/README.md

We probably should write a guide or something for the library in general, but I (lazily) just kind of rely on godoc for that. The top-level README links to a bunch of docs around implementation of things, but not necessarily the interfaces, e.g.

* https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/v1/tarball/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/v1/daemon/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/v1/partial/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/transport/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/authn/README.md
* https://github.com/google/go-containerregistry/blob/main/pkg/v1/stream/README.md

I've also been meaning to write a REGRET.md (or similar) to document a handful of library design goofs and interface mistakes :/

If you do come across something that you think could be clearer or a package that needs a README, please do file an issue and/or a PR. I'm kind of cursed with the knowledge of the code, so it's harder to see the gaps, even though I know they're there.
