### ISSUE TITLE
How to follow this project / expected release cadence

### ISSUE THREAD

**Issue by aaronshurley** [google/go-containerregistry#1094]
👋 Hi there! I'm interested if there are ways for me to track release plans or better understand when releases will be published? We have a bug fix that we're expecting in v0.6.0 (or v0.5.2) and I'm not sure when to expect it. I'm not trying to add any urgency here, just asking to see if there are ways for me to discover this information. Thanks!

**Comment by imjasonh** [comment]
The project doesn't currently follow a regimented release schedule, mostly we just cut releases whenever there's some semi-serious bugfix or enough new features that people want to use to warrant it.

What's the fix you're expecting? We can probably cut a release any time.
wdyt @jonjohnsonjr

**Comment by aaronshurley** [comment]
Gotcha. This is the fix we're interested in: https://github.com/google/go-containerregistry/pull/1041

**Comment by jonjohnsonjr** [comment]
Just cut v0.6.0: https://github.com/google/go-containerregistry/releases/tag/v0.6.0

Yeah, as Jason said, it's mostly as needed (by me or Jason), otherwise on request (by e.g. you). I realize that's not great, but we're open to ideas/feedback. I know @hasheddan talked about better release infra at one point.
