### ISSUE TITLE
Support saving image as tarball

### ISSUE THREAD

**Issue by paralika** [google/go-containerregistry#1132]
There are options to export and pull image contents to the tarball. Can crane support saving the image to tarball? I am trying to find out something like `docker save`.

**Comment by jonjohnsonjr** [comment]
`crane pull` is essentially the same as `docker pull && docker save`, just without the intermediate step of a docker daemon. You should get a very similar tarball to what `docker save` produces.

There's a `--format=legacy` to make that tarball even more similar to what `docker save` would produce, but most tools can parse both outputs.

**Comment by paralika** [comment]
Thanks @jonjohnsonjr  It helps.

**Comment by evgenymo** [comment]
I just tried something similar with nginx:latest but there is still a size difference
```
SIZE1         SIZE2
180.3M        185.3M
```

I also tried with `--format=legacy` still the same

BTW, until i discovered this issue i tried to use export which is the logical choice of an action since it says it produces a tarball and it doesn't perform the same actions as `docker save` am i the only one who was confused by the naming?
