### ISSUE TITLE
Publically-available GitHub Action for crane

### ISSUE THREAD

**Issue by jdolitsky** [google/go-containerregistry#1151]
Please see https://github.com/opencontainers/container-images/blob/14544173b3a529d7c478ffa29a88b5e4c7de2686/.github/workflows/golangci-lint.yml#L22

**Comment by imjasonh** [comment]
There's one available here: https://github.com/imjasonh/setup-crane

IIRC due to the `google` GitHub org's policies, Actions can't be published under this org (I tried [for ko](https://github.com/imjasonh/setup-ko) as well). If someday this repo moves to a less restrictive org we can bring the action in-house.
