### ISSUE TITLE
New release for patching docker/cli CVE

### ISSUE THREAD

**Issue by xtremerui** [google/go-containerregistry#1174]
Hi, not sure if it should be an issue first of all. Apologies if this is not an appropiate place for my request.

Recently the vulnerabilities scanning in our CI reported github.com/docker/cli with https://avd.aquasec.com/nvd/cve-2021-41092/.

The CVE is patched in 20.10.9 and I can see here in master go.mod it is already bumped.

Is it possible to release a new version of go-containerregistry so we all could benefit in downstreams? A patched release that just including github.com/docker/cli@20.10.9 is good enough. Thx a lot!

**Comment by imjasonh** [comment]
This is a fine place to make this request. We had planned to cut a go-containerregistry release anyway (last week actually, I think 😬) and so that should be coming soon regardless.

Re: that specific CVE, I think we're pretty confident that we aren't actually susceptible to that vulnerability, even though we depend on that package at the vulnerable version. Looking at the patch that fixed the vulnerability, it seems like it only affects code we don't use. So it should be safe (we think) to ignore that vulnerability warning.

Regardless, we should cut a release anyway, which should take care of the warnings.
