### ISSUE TITLE
question: manifest unknown: Failed to fetch "v0.6.1"

### ISSUE THREAD

**Issue by voor** [google/go-containerregistry#1224]
Looks like github-actions did a patch release 3 days ago, it's advertising the following container:

```
gcr.io/go-containerregistry/crane:v0.6.1
```

Except that this tag does not exist in the given registry.

**Comment by imjasonh** [comment]
@jonjohnsonjr cut the release, and thoughtfully disabled image publishing beforehand because our cloudbuild.yaml would have published :v0.6.1 as :latest otherwise.

We should probably get around to publishing a :v0.6.1 image at some point, but I don't think it's urgent. Unless you're seeing some other unusual or broken behavior?
