### ISSUE TITLE
question: Is it possible to query all tags for a given digest using crane

### ISSUE THREAD

**Issue by marcofranssen** [google/go-containerregistry#1297]
Is there a possibility to query all tags for a given digest using crane?

If not possible, can this be implemented on crane?

Happy to contribute with some guidance.

**Comment by jonjohnsonjr** [comment]
There is no way to _efficiently_ do this in general because there is not an API for it. This would be a good use case to bring up in https://github.com/opencontainers/wg-reference-types

If you're using Artifact Registry or GCR, the tag listing response has additional information, so this would work:

```
$ gcrane ls --json mirror.gcr.io/library/ubuntu | jq '.manifest["sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be"].tag'
[
  "20.04",
  "focal",
  "latest"
]
```

For other registries, you'd have to query each tag, something like this:

```
$ digest=sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be
$ for tag in $(crane ls mirror.gcr.io/library/ubuntu); do if [ $digest == $(crane digest mirror.gcr.io/library/ubuntu:$tag) ]; then echo $tag; fi done
20.04
focal
latest
```

**Comment by jonjohnsonjr** [comment]
Closing this because I think the general answer is "no" unless new registry APIs are implemented (or you use either of the two options presented).
