### ISSUE TITLE
v1/remote/options: Add `WithTimeout(timeout time.Duration)` Option

### ISSUE THREAD

**Issue by Dentrax** [google/go-containerregistry#1313]
I think currently we unable to set custom `timeout` in `options{}` [struct](https://github.com/google/go-containerregistry/blob/329563766ce8131011c25fd8758a25d94d9ad81b/pkg/v1/remote/options.go#L36-L49) to use it later in `v1/remote/write`. I'm not saying _per layer upload_ timeout, I mean setting _overall timeout_.

```golang
type options struct {
 ...
 timeout time.Duration
}


func WithTimeout(timeout time.Duration) Option {
	return func(o *options) error {
		o.timeout = timeout
		return nil
	}
}
```

And what then? Should we re-configure the DefaultTransport's Timeout, since the following fields are hard-coded?

```golang
var DefaultTransport = &http.Transport{
	DialContext: (&net.Dialer{
		Timeout:   5 * time.Second,
		KeepAlive: 30 * time.Second,
	}).DialContext,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
```

Or should we override the `o.context` by wrapping something like:

```golang
func WithTimeout(timeout time.Duration) Option {
	return func(o *options) error {
		o.context = context.WithTimeout(o.context, timeout)
		return nil
	}
}
```

**Comment by imjasonh** [comment]
I'd suggest just using [`remote.WithContext`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#WithContext) and a context with a deadline or timeout to achieve this.

Wrapping it in `WithTimeout` gets complicated since we need to do something with the returned `CancelFunc`.

If you provide a context we (should) use it in all HTTP calls to override the hard coded transport timeouts. If we missed one, or if that's not working as expected, let me know.

**Comment by Dentrax** [comment]
Makes sense, thanks. Resolved by writing the following logic:

```go
ctx := context.TODO()
ctx, _ = context.WithTimeout(ctx, 5*time.Second)

var opts []remote.Option
opts = append(opts, remote.WithContext(ctx))
...
```
