### ISSUE TITLE
question: crane: How to pull images of two architectures at the same time，like crane pull alipline:latest   alipline.tar.gz --platform linux/amd64,linux/arm64

### ISSUE THREAD

**Issue by bryant-rh** [google/go-containerregistry#1326]
How to pull images of two architectures at the same time，like :
crane pull alipline:latest   alipline.tar.gz --platform linux/amd64,linux/arm64

**Comment by imjasonh** [comment]
The default output format is only suitable to store one image's worth of layer information. If you specify `--format=oci` (since https://github.com/google/go-containerregistry/pull/1208) it will fetch all platforms of the image, and you can inspect the results to find only the platforms you want.

This is an incomplete answer, I realize, since it requires more work to explore the produced OCI layout, and isn't as easy as `--platform=A,B`. We haven't really had any requests for this behavior before. Can you share a bit about what you're trying to achieve?

**Comment by bryant-rh** [comment]
> 

thank you very much for your reply， --format=oci  is enough for me。
I just want to package the image specifying multiple arch

**Comment by bryant-rh** [comment]
> The default output format is only suitable to store one image's worth of layer information. If you specify `--format=oci` (since #1208) it will fetch all platforms of the image, and you can inspect the results to find only the platforms you want.
> 
> This is an incomplete answer, I realize, since it requires more work to explore the produced OCI layout, and isn't as easy as `--platform=A,B`. We haven't really had any requests for this behavior before. Can you share a bit about what you're trying to achieve?

But there is a new problem，How to import oci format image to machine through docker or ctr command。
and I tried to package the exported oci image and copied it to the k3s directory: ”rancher/k3s/agent/images/“, and the following error was prompted:
level=error msg="Error encountered while importing /data/rancher/k3s/agent/images/a.tar.gz: unrecognized image format"

**Comment by imjasonh** [comment]
I'm not very familiar with k3s, but I would assume it only supports loading one architecture (at least that's how it sounded in https://github.com/google/ko/pull/665), so maybe this would be resolved by only pulling and loading the one image?

**Comment by bryant-rh** [comment]
> I'm not very familiar with k3s, but I would assume it only supports loading one architecture (at least that's how it sounded in [google/ko#665](https://github.com/google/ko/pull/665)), so maybe this would be resolved by only pulling and loading the one image?

it‘s great，thank you very much for your reply！
