### ISSUE TITLE
ggcr: unable to reuse authenticated transport with v1/remote

### ISSUE THREAD

**Issue by benmoss** [google/go-containerregistry#1336]
### Describe the bug
I'd like to initialize an http.RoundTripper after doing an auth handshake and then use it to perform several requests to a repository. Right now the v1/remote functions all create a new http.RoundTripper via `transport.NewWithContext`, even if you pass one to the method via the `option.WithTransport` call.

### To Reproduce
I made this sample app to demonstrate the problem: https://gist.github.com/benmoss/620ec0b372be90c2471fdff3d80564fb

With the debug logs enabled you can see several calls to `GET https://gcr.io/v2/`, which should be unnecessary since we already know it allows anonymous access.

### Expected behavior
It should skip the extraneous /v2 pings

### Additional context
I was thinking maybe it would make sense for registry to do some type check on the transport, similar to how we do a check for a `transport.Wrapper` right now to skip some wrapping, but in this case for authentication. Maybe the user can just pass a `transport.Wrapper` and that will be used? I'm not sure why not other than its a change in the contract.

Support for using the same transport to talk to multiple registries would also get more complicated, but this is similar to [remote.MultiWrite](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote@v0.8.0#MultiWrite)

**Comment by benmoss** [comment]
xref #740

**Comment by jonjohnsonjr** [comment]
So the way I was planning to tackle this looks roughly like:

```go
package transport

func NewSomething(t http.RoundTripper, kc authn.Keychain) http.RoundTripper {
  return multiTransport{t, kc}
}
```

This would take all the same logic from the `transport` package that we currently do based on the ping response and just do it lazily whenever we get a 401/403 from the registry. It would also not be scoped to a single registry or repository, so we could reuse it across multiple registries. This would also allow us to remove [this caveat](https://github.com/google/go-containerregistry/blob/7b4be6bb31395ead003b6841110aca4c4119cddd/pkg/v1/remote/multi_write.go#L35) in `remote.MultiWrite`.

To reduce how much we hammer token servers, we need some logic around caching requests based on the realm and scope of the registry token.

We'd move everything in `remote` over to using this new transport instead of the ping-based one, and if callers want to reuse it across multiple functions in `remote`, they can instantiate one manually and pass it via `remote.WithTransport`.

**Comment by jonjohnsonjr** [comment]
https://github.com/google/go-containerregistry/pull/1396 makes this possible, but it's clunkier than what I described above, so I'm inclined to leave this open.

**Comment by jonjohnsonjr** [comment]
@vito FYI -- I know this came up in https://github.com/google/go-containerregistry/issues/740
