### ISSUE TITLE
ggcr: Docker version upgrade ?

### ISSUE THREAD

**Issue by billrein** [google/go-containerregistry#1361]
Hi, Is there any plan to upgrade the version of docker and used by this project? It's currently at github.com/docker/cli v20.10.12 and github.com/docker/docker v20.10.12. It seems that docker/docker <= 20.10.14 have a remote privilege vulnerability

**Comment by imjasonh** [comment]
I'll bump all our deps in https://github.com/google/go-containerregistry/pull/1317, including docker/docker.

FWIW, this package should not be susceptible to the vulnerability reported in docker/docker, since we don't use the vulnerable functionality. But I understand wanting quieter vuln scanners too 😄
