### ISSUE TITLE
ggcr: Tags for github.com/google/go-containerregistry/pkg/authn/kubernetes

### ISSUE THREAD

**Issue by ibuildthecloud** [google/go-containerregistry#1381]
It would be nice if there were tags for the submodules in this project, specifically github.com/google/go-containerregistry/pkg/authn/kubernetes.  I know it's a headache, but its just that I'm picking up ggcr using a tag like v0.9.0 and I want to ensure I have the correct submodule for that tag or if there's no relation that's fine, but that would be clear because the submodule might be like v0.1.0 when ggcr is v0.9.0.

**Comment by jonjohnsonjr** [comment]
I'll need to take a look at our release setup to make sure we do the right thing for submodule tags (I think we probably don't), but agreed we should do this.

**Comment by imjasonh** [comment]
Does this just mean we should have a GitHub Action that reacts to the creation of tag `v0.X.Y` by creating an equivalent:
- `pkg/authn/kubernetes/v0.X.Y`
- `pkg/authn/k8schain/v0.X.Y`
- `cmd/krane/v0.X.Y`

I don't think we want to get into having submodules at different versions than the main module.

To confuse matters even more, because we [`replace github.com/google/go-containerregistry => ../../../`](https://github.com/google/go-containerregistry/blob/main/pkg/authn/k8schain/go.mod#L6`) (and those aren't respected when folks depend on that submodule), we might get into a scenario where `pkg/authn/kubernetes@v0.10.0` depends on `ggcr@v0.9.0` until dependabot bumps it for us.

One way to fix that would be to have `pkg/authn/kubernetes@v0.10.0` be one commit ahead of `ggcr@v0.10.0`, where that commit is bumping its ggcr dep.

All of this is gross. Can we just move these to separate repos?

**Comment by ibuildthecloud** [comment]
Submodules in general are gross.  I'm all for moving to different repos.  But yes, what I'm asking for is if you keep the current structure that you create a `pkg/authn/kubernetes/v0.X.Y` tag.

**Comment by imjasonh** [comment]
This would be fixed in https://github.com/google/go-containerregistry/pull/1708 if there's still interest we can push that ahead.
