### ISSUE TITLE
question: optimal way to extract only a directory and compress it using crane

### ISSUE THREAD

**Issue by oscarnevarezleal** [google/go-containerregistry#1382]
Hi! First of all thank you for this amazing tools.

I've seen a lot of one line hacks using  `crane` and `tar` what makes me believe there must be an optimal way to accomplish my task.

Currently:

````
# Having a container image called myapp
crane export myapp app.tar
# I extract only the /workspace directory
tar -xvpf app.tar /workspace -C /
# then compress it again to create a new file
tar -cf workspace.tar workspace
````

Thanks in advance.

**Comment by jonjohnsonjr** [comment]
With `crane` you're going to end up downloading everything, at least. You could avoid writing everything out to disk by filtering what is extracted (`crane export $IMAGE | tar -xf - /workspace`, I think) but that's not great still...

Unfortunately, I don't think there's a way to get much better than that because you have to download every layer to flatten them into one filesystem.

Hope that's helpful? 😅

**Comment by oscarnevarezleal** [comment]
@jonjohnsonjr it is helpful, thank you.
