### ISSUE TITLE
crane: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by developer-guy** [google/go-containerregistry#1383]
### Describe the bug

We (w/@dentrax) encountered an error while working with rebasing option.

We typed `crane rebase` without providing any argument and got the following error:

```shell=
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/google/go-containerregistry/cmd/crane/cmd.NewCmdRebase.func1(0xc000286f00?, {0x1862e60?, 0x0?, 0x0?})
        github.com/google/go-containerregistry/cmd/crane/cmd/rebase.go:41 +0xfe6
github.com/spf13/cobra.(*Command).execute(0xc000286f00, {0x1862e60, 0x0, 0x0})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000280000)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.4.0/command.go:895
main.main()
        github.com/google/go-containerregistry/cmd/crane/main.go:34 +0xce
```

### To Reproduce

just type `crane rebase` without giving any arguments.

### Expected behavior

What we expected from this is displaying the help message without throwing an error.

### Additional context

- Output of `crane version`: 0.9.0
- Registry used (e.g., GCR, ECR, Quay)

**Comment by developer-guy** [comment]
We're willing to help to fix this, would you mind assigning it to us, thanks.

**Comment by imjasonh** [comment]
Yep, `crane rebase` requires at least one arg, and not having it will panic, here, like you say:

https://github.com/google/go-containerregistry/blob/7fc806eebf5bec4f1e7e58d9b9103db4d9460cf6/cmd/crane/cmd/rebase.go#L41

I think we might just need [`cobra.MinimumNArgs(1)`](https://pkg.go.dev/github.com/spf13/cobra#MinimumNArgs) instead of [`cobra.MaximumNArgs(1)`](https://pkg.go.dev/github.com/spf13/cobra#MaximumNArgs).

If you'd like to send a PR that'd be great! Thanks for finding this.
