### ISSUE TITLE
daemon.Write does not close unix socket

### ISSUE THREAD

**Issue by testwill** [google/go-containerregistry#1417]
daemon.Write does not close unix socket

code like this :

	tag, _ := name.NewTag(imageFullName)

	str, err := daemon.Write(tag, img, daemon.WithContext(ctx))
	if err != nil {
		fmt.Println("daemon.Write function failed")
		return
	} else {
		fmt.Println(str)
	}

run it:

```
# ./image_pull  -img 192.168.1.94:443/library/busybox:latest
3708686
{"stream":"Loaded image: 192.168.1.94:443/library/busybox:latest\n"}


osquery result:
osquery> select * from process_open_sockets where pid=3708686;
+---------+----+----------+--------+----------+---------------+----------------+------------+-------------+------+-------------+---------------+
| pid     | fd | socket   | family | protocol | local_address | remote_address | local_port | remote_port | path | state       | net_namespace |
+---------+----+----------+--------+----------+---------------+----------------+------------+-------------+------+-------------+---------------+
| 3708686 | 6  | 26290076 | 2      | 6        | 192.168.1.41  | 192.168.1.94   | 51624      | 443         |      | ESTABLISHED | 4026531992    |
| 3708686 | 7  | 26292673 | 1      | 0        |               |                | 0          | 0           |      |             | 4026531992    |
+---------+----+----------+--------+----------+---------------+----------------+------------+-------------+------+-------------+---------------+
```

fd 7 leak

**Comment by imjasonh** [comment]
As far as I know there's not a lot we can do directly here.

Tracing it through, `daemon.Write` basically just calls Docker's `client.ImageLoad`:

https://github.com/google/go-containerregistry/blob/31786c6cbb82d6ec4fb8eb79cd9387905130534e/pkg/v1/daemon/write.go#L50

which calls `postRaw`:

https://github.com/google/go-containerregistry/blob/31786c6cbb82d6ec4fb8eb79cd9387905130534e/vendor/github.com/docker/docker/client/image_load.go#L21

which ends up calling `doRequest`:

https://github.com/google/go-containerregistry/blob/31786c6cbb82d6ec4fb8eb79cd9387905130534e/vendor/github.com/docker/docker/client/request.go#L113

which calls `cli.client.Do`:

https://github.com/google/go-containerregistry/blob/31786c6cbb82d6ec4fb8eb79cd9387905130534e/vendor/github.com/docker/docker/client/request.go#L125

which is just a standard `*http.Client`

https://github.com/google/go-containerregistry/blob/31786c6cbb82d6ec4fb8eb79cd9387905130534e/vendor/github.com/docker/docker/client/client.go#L77

So it seems like the intention is that the HTTP client that connects to the local socket isn't supposed to close that connection right away, in case it needs it again.

I suspect the `docker` CLI has the same behavior, which makes sense, since it probably makes lots of requests to the daemon during its normal operation, and the overhead of opening and closing the connection over and over would be wasteful.

Is there a problem you're experiencing with this behavior? It's possible you could use [`daemon.WithClient`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/daemon#WithClient) with a Docker client configured to close the connection more aggressively, using [`client.NewClientWithOpts`](https://pkg.go.dev/github.com/docker/docker/client#NewClientWithOpts) and [`client.WithDialer`](https://pkg.go.dev/github.com/docker/docker/client#WithDialer).

**Comment by testwill** [comment]
When I use crane.Save and go-dockerclient's LoadImage function, this problem does not appear. The file descriptor mentioned above is leaked every time it is called, and these sockets always exist.

**Comment by testwill** [comment]
code  like this :
	img, err = crane.Pull(imageFullName, crane.WithTransport(rt))
	if err != nil {
		fmt.Println("0000000000000 :", err.Error())
		return
	}
	imagePath := "test0001.tar"
	if err != nil {
		fmt.Println("1111111111111 :", err.Error())
		return
	}
	err = crane.Save(img, imageFullName, imagePath)

	client, _ := docker.NewClientFromEnv()
	tar, err := os.Open(imagePath)
	if err != nil {
		fmt.Println(err)
		return
	} else {
		defer tar.Close()
	}
	opts := docker.LoadImageOptions{InputStream: tar}
	err = client.LoadImage(opts)
	if nil != err {
		fmt.Println(err)
		return
	}

**Comment by testwill** [comment]
pr, pw := io.Pipe()
	go func() {
		pw.CloseWithError(tarball.Write(tag, img, pw))
	}()

	client, _ := docker.NewClientFromEnv()
	opts := docker.LoadImageOptions{InputStream: pr}
	err = client.LoadImage(opts)
	if nil != err {
		fmt.Println(err)
		return
	}


like this can be ok

**Comment by imjasonh** [comment]
That sounds like [go-dockerclient](https://github.com/fsouza/go-dockerclient) is doing something smarter than docker/docker's client to clean up after itself.

If you can demonstrate that there's a way to call docker's `ImageLoad` or similar without leaking, then this is a bug in our code, otherwise it's a bug in Docker's client, or intended behavior (by them).

In theory we could switch from using docker's client to go-dockerclient, but I'd be a little nervous about that since this is a pretty complex area of the code, and I'd prefer to rely on Docker's own client code if we can.

**Comment by testwill** [comment]
docker's ImageLoad have the same problem

**Comment by testwill** [comment]
Is there a leak just by using the daemon package?
