### ISSUE TITLE
crane: mutate and append adds layer with docker mediaType regardless of what base image uses 

### ISSUE THREAD

**Issue by thesayyn** [google/go-containerregistry#1427]
### Describe the bug

`mutate` or `append` adds new layers as `DockerLayer` instead of `OCILayer` when the base image only has OCI mediaTypes.
 This behavior leads to mixed mediaTypes.
 
### To Reproduce

```
crane mutate thesayyn/debian:oci --append <some>.tar. <your-registry>:oci-mixed
``` 

### Expected behavior

The newly added layer should have the mediaType `application/vnd.oci.image.layer.v1.tar+gzip` instead of `application/vnd.docker.image.rootfs.diff.tar.gzip`. Perhaps this could be controlled by a global flag? Maybe `--preferred-media-types=oci|docker`?

### Additional context

- Output of `crane version`:  0.11.0
- Registry used (e.g., GCR, ECR, Quay): Docker

**Comment by jonjohnsonjr** [comment]
Two issues, I think:

1. By default, we use docker media types for layers.
2. By default, `empty.Image` is a docker media type.

We can (and should) make `crane append` use the image's media type in order to determine the media type of the appended layer(s). We should add `WithMediaType` options to `stream` and `tarball` and plumb that through based on the base image's media type.

However, that doesn't help us for the `empty.Image` case. We could have a flag that flips `empty.Image` into an OCI image (and let that determine the layer media types as well), or we could have separate flags that control layer media types and image media types...

I'd lean towards just adding `--oci` to flip `empty.Image` and not allow folks to intermingle different families of media types with `crane append`. If you want to do something unexpected like that (e.g. to test registry behavior), you could use `crane edit`.
