### ISSUE TITLE
FR: Support resumable push

### ISSUE THREAD

**Issue by LiuShuaiyi** [google/go-containerregistry#1448]
Hi team,

I wonder if it's possible to support resumable push in go-containerregistry. We found that pushing XL image layers (we have images with 40GB+ layers) often fails under choppy network conditions or when the servers are throttled, and it seems go-containerregistry uploads the entire image layer in one single PATCH request instead of splitting a layer into chunks, so every time a layer push failed it had to start all over again. 

Supporting resumable push in go-containerregistry will help our use cases greatly I think. If this is not possible, would also love to learn if there are other OCI client libraries that already support this functionality. 

Thanks

References:

- https://docs.docker.com/registry/spec/api/
- https://github.com/opencontainers/distribution-spec/blob/main/spec.md#resumable-push
- https://github.com/moby/moby/issues/4872
- https://github.com/goharbor/harbor/issues/15150
- https://github.com/regclient/regclient

**Comment by imjasonh** [comment]
This is definitely something we could support, it just needs someone motivated to contribute it. I'd be happy to review designs and API changes and code.

The first step would be API changes -- how should the user express they want a resumable push, and with what chunk sizes? That's probably best expressed as a `remote.Option`, something like `WithChunkSize(int bytes)`. Then a call like `remote.Write(ref, img, remote.WithChunkSize(100))` sends 100-byte chunks.

We'd still go through `writeImage`, which initiates an upload, but instead of [`streamBlob`](https://github.com/google/go-containerregistry/blob/9a5c14ada6ffae772793231c186a50d911668e72/pkg/v1/remote/write.go#L312) doing one big `PATCH` request, it would call some other method to split the stream into chunks and write those separately, retrying if they fail with retryable errors.

The upload finalization step is the same in either case.

The test registry in `pkg/registry` will also need to add support for appending to existing uploads; IIRC it only supports the one-big-push mode since that's all the tests needed.
