### ISSUE TITLE
question: Does the library support extracting image layer compressed using bzip (.tar.bz2)

### ISSUE THREAD

**Issue by nan-yu** [google/go-containerregistry#1480]
Hello, 

I archived my files into a bzipped tarball and then pushed it as an OCI image using `oras`:
```
tar -cjf test-image.tar.bz2 my-files/
oras push [OCI-REGISTRY] test-image.tar.bz2
```

Then I used the library to extract the image: https://github.com/google/go-containerregistry/blob/v0.12.0/pkg/v1/mutate/mutate.go#L222.
I couldn't get anything extracted.

I dug into the code and found out it uses the gzip library to uncompress the image: https://github.com/google/go-containerregistry/blob/v0.12.0/pkg/v1/partial/compressed.go#L48.

I'm wondering if there's any plan to support uncompressing the `.tar.bz2` format?

FYI @mathieu-benoit

**Comment by jonjohnsonjr** [comment]
No, but also `oras` appears to be broken. The layer it pushes claims to be an OCI layer:

```
$ crane manifest $REPO@sha256:ad31171691bf05a926fd1d411b6a263c00fe4f48eb45aa511849196519f6d706 | jq  .layers[0].mediaType -r
application/vnd.oci.image.layer.v1.tar
```

But it's not:
```
$ crane blob $REPO@$(crane manifest $REPO@sha256:ad31171691bf05a926fd1d411b6a263c00fe4f48eb45aa511849196519f6d706 | jq  .layers[0].digest -r) | file -
/dev/stdin: bzip2 compressed data, block size = 900k
```

So even if we did support `bz2`, this still wouldn't work.

**Comment by mathieu-benoit** [comment]
Hi @jonjohnsonjr, if I try your last command in error with `.tar` file with which I did an `oras push`, ``, I got the error:
```
/dev/stdin: POSIX tar archive (GNU)
```
But if I do: `crane blob $REPO@$(crane manifest $REPO:cf | jq  .layers[0].digest -r) > test-cf2.tar`, I can have the same file.

Same for the `.bz2` you illustrated, if I dod `crane blob $REPO@$(crane manifest $REPO:cjf | jq  .layers[0].digest -r) > test-cjf2.tar.bz2`, I can have the exact same file I previously uploaded via `oras push`.

Thoughts? What's the difference between your `| file -` and  my `> file.tar`?

**Comment by imjasonh** [comment]
`| file -` invokes the [Unix `file` command](https://en.wikipedia.org/wiki/File_(command)), which reports information about the file, either passed in as an arg (`file foo.txt`) or piped in (`cat foo.txt | file -`).

So Jon's command was just saying that `crane blob` returned a file that was `bzip2 compressed data`, even though the layer's mediaType was reported as `layer.v1.tar` (no bzip).

This makes it hard for tools like `crane` to automatically tell what to do, since they rely on the `mediaType` to accurately describe what the data represents.

**Comment by mathieu-benoit** [comment]
Thanks for clarifying @imjasonh.

But here is my simple test with a simple `.tar` file:
```
TAG=test
cat <<EOF> test.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
EOF
tar -cf test.tar test.yaml
crane append -f test.tar -t $REPO:$TAG
```
All of this working successfully, I can even successfully get back the `test.tar` file via: `crane export $REPO:$TAG - | tar -xvf -`.

But when running `crane blob $REPO@$(crane manifest $REPO:$TAG | jq  .layers[0].digest -r) | file -`, I'm getting this error:
```
/dev/stdin: gzip compressed data, max speed
```
Thoughts?

Just need to understand this part to further continue the discussion with `.bz2` I think. Thanks!

**Comment by imjasonh** [comment]
When you append the tar file, `crane append` gzips it (using the best-speed compression) before uploading it. It should also set the `mediaType` correctly, which you can check with `crane manifest $REPO:$TAG | jq '.layers[0].mediaType')` and see that it's `tar+gzip` and not just `tar`.

`crane` uses gzip for this, and not bzip. If you `crane append`ed a bzipped tar, I would expect `crane` to gzip the already-bzipped tar, since it's not already, but I'm not sure.

To answer the question in the issue title: In general there isn't support in `crane` or go-containerregistry for bzip, the way there is for automatically gzipping/gunzipping. We could add it, the main difficulties would be around how to express this well in the Go APIs and in the `crane` CLIs, possibly with a flag.
