### ISSUE TITLE
gcrane: configured gcloud credentials not used for a service account 

### ISSUE THREAD

**Issue by christopheblin** [google/go-containerregistry#1496]
### Describe the bug

I am using a gitlab pipeline to copy an image from project1 to project2 (I redacted the names of the projects and of the Git tags)

The IAM credentials on project2 includes  "Artifact registry writer" role

The IAM credentials on project1 includes  "Artifact registry reader" role

The docker image is google/cloud-sdk:latest

The debug message clearly states that credHelpers is configured for europe-west1-docker.pkg.dev buth then there is an error message `No matching credentials were found for "europe-west1-docker.pkg.dev"`

Maybe there is something in the gcrane CLI that is not using the service account configured with gcloud CLI ?

### To Reproduce
        - curl -L https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz -o go-containerregistry.tar.gz
        - tar -zxvf go-containerregistry.tar.gz && chmod +x gcrane
        - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
        - gcloud auth configure-docker europe-west1-docker.pkg.dev
        - echo ----debug---- && cat /root/.docker/config.json
        - ./gcrane cp europe-west1-docker.pkg.dev/project1/apps/xxx:$SRC_TAG europe-west1-docker.pkg.dev/project2/xxx:$SRC_TAG 

```
$ gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
Activated service account credentials for: [glb-gitlab@project2.iam.gserviceaccount.com]
$ gcloud auth configure-docker europe-west1-docker.pkg.dev
Adding credentials for: europe-west1-docker.pkg.dev
After update, the following will be written to your Docker config file located 
at [/root/.docker/config.json]:
 {
  "credHelpers": {
    "europe-west1-docker.pkg.dev": "gcloud"
  }
}
Do you want to continue (Y/n)?  
Docker configuration file updated.
$ echo ----debug---- && cat /root/.docker/config.json
----debug----
{
  "credHelpers": {
    "europe-west1-docker.pkg.dev": "gcloud"
  }
}$ ./gcrane cp europe-west1-docker.pkg.dev/project1/apps/xxx:$SRC_TAG europe-west1-docker.pkg.dev/project2/xxx:$SRC_TAG
2022/11/28 10:06:26 Copying from europe-west1-docker.pkg.dev/project1/apps/xxx:redacted to europe-west1-docker.pkg.dev/project2/xxx:redacted
2022/11/28 10:06:27 No matching credentials were found for "europe-west1-docker.pkg.dev"
Error: fetching "europe-west1-docker.pkg.dev/project1/apps/xxx:redacted": GET https://europe-west1-docker.pkg.dev/v2/token?scope=repository%3Aproject1%2Fapps%2Fxxx%3Apull&service=: UNAUTHORIZED: failed authentication
```

### Expected behavior

The gcrane should use the credentials that were configured with gcloud

Edit : I added a debug command to show the content of the docker config

**Comment by jonjohnsonjr** [comment]
That warning is fairly misleading, we should fix that.

The way `gcrane` fetches credentials is by looking for application default credentials (in [this order](https://pkg.go.dev/golang.org/x/oauth2@v0.2.0/google#FindDefaultCredentialsWithParams)), falling back to shelling out to `gcloud`, falling back to using the docker config file.

Because you're running on gitlab, I would guess that `gcrane` is picking up the service account from the GCE metadata server and using those credentials.

This is something that would be improved by https://github.com/google/go-containerregistry/pull/1446 once we settle on a solution there so that we would actually fall back when credentials fail rather than only using the first credentials we find.

Until then, some workarounds:

1. Use [workload identity](https://docs.gitlab.com/ee/ci/cloud_services/google_cloud/) instead of service account keys.
2. Set `GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-service-key.json` so that [`FindDefaultCredentialsWithParams`](https://pkg.go.dev/golang.org/x/oauth2@v0.2.0/google#FindDefaultCredentialsWithParams) picks that up instead of the metadata server.
3. Use `crane` instead of `gcrane`. This isn't great if you need some `gcrane`-specific functionality.

If none of those work or are acceptable, there might be something else going on, and we should make this easier to debug.

**Comment by christopheblin** [comment]
@jonjohnsonjr Thanks for the very detailed explanation

I tested the commands with a simple "docker run google/cloud-sdk" and they worked, so good catch for understanding that it was tied to the gitlab context 👍 

The workload identity seems very promising, unfortunately I do not have the time for testing it right now 😢 

The env var GOOGLE_APPLICATION_CREDENTIALS works, so this is what I'm going to use

Thanks again for your time
