### ISSUE TITLE
question: Can this library (daemon.Write) write to Containerd, or only Docker daemons?

### ISSUE THREAD

**Issue by tculp** [google/go-containerregistry#1526]
I've successfully used this library to load a tarball and write to the docker daemon, both on my local machine and in Kubernetes. However, dockerd as a container backend is being phased out. I haven't been able to find in the documentation whether or not this library can write to a containerd daemon's image registry. Can this be done?

I see the GGCR_EXPERIMENT_ESTARGZ env var which mentions containerd, but does this mean that the only way to write to containerd is by loading a tarball into layers with this experiment enabled, building an image from the layers, and then calling daemon.Write?

**Comment by jonjohnsonjr** [comment]
It shouldn't be too difficult to implement -- e.g. `ko` shells out to `ctr` to load images for kind clusters: https://github.com/ko-build/ko/blob/main/pkg/publish/kind/write.go

... but it's not something we natively have in this library. I'm not sure if we'd want to bring it in due to the number of dependencies we might pull in, but I'd be interested in what that looks like.
