### ISSUE TITLE
question: Getting uncompressed image size

### ISSUE THREAD

**Issue by panteparak** [google/go-containerregistry#1554]
Based on this [Crane tutorial](https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md#get-total-image-size) where it seems to be possible to get an image size using `Crane`. But it seems to only shows a compressed size and not an actual uncompressed image size.

Is this possible to get an uncompressed image size with this library?

**Comment by imjasonh** [comment]
```
$ crane export cgr.dev/chainguard/static - | tar -xzf - --to-stdout | wc -c
 1378616
```

(based on https://stackoverflow.com/a/16888360)

Compare this to the compressed size:

```
$ crane manifest cgr.dev/chainguard/static --platform=linux/amd64 | jq '.config.size + ([.layers[].size] | add)'
486925
```

So 486 KB compressed, 1.37 MB uncompressed.

There might be other ways to do this, but they'd probably all start with `crane export <img>` which gives you a gzipped-tar stream, which you can pass to other things.

Note that this effectively pulls and decompresses the whole image, since there's no way to do this purely given image metadata. So this will be fast for small images, and slower for larger images.

**Comment by jonjohnsonjr** [comment]
It's also surprisingly hard to define the uncompressed size of an image. Some possible interpretations...

The most straightforward answer is to sum the sizes of the uncompressed layers, but doing that requires downloading and decompressing each layer, which can be slow for large layers:

```
$ time curl -s "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/67/677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8/data?verify=1675710993-K6JOnbGzhtQ492I28V%2FmyVUfwWI%3D" \
  | gunzip | wc -c
80326656

real	0m0.774s
user	0m0.668s
sys	0m0.169s

```


If you know the uncompressed size of the layers is under 4GB, you can do this more efficiently because gzip stores the input size modulo 2^32 in the trailer:

```
$ time curl -s -H "Range: bytes=-4" "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/67/677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8/data?verify=1675710993-K6JOnbGzhtQ492I28V%2FmyVUfwWI%3D" \
  | hexdump --format '4/4 "%d"'
80326656

real	0m0.141s
user	0m0.061s
sys	0m0.032s
```

But that's still the size of the tarball. If you're storing the layers uncompressed, this should be correct, but if you want to know the size on disk after untarring all the layers, it's difficult to know because this wouldn't take into account filesystem metadata or deduplicated files.

Jason's answer of `crane export` is pretty good in that it takes care of deleted files and duplicated files, but again it can be slow and assumes you're not doing anything interesting like deduplicating layers across multiple images.

So it's possible to estimate the size, sometimes even quickly, but it depends on how you're storing the image after it's decompressed.
