### ISSUE TITLE
question: add support for version constraint in crane ls command 

### ISSUE THREAD

**Issue by tuananh** [google/go-containerregistry#1605]
I was thinking something like this, similar to what Helm has

```sh
# helm search repo nginx-ingress --version ^1.0.0
crane ls myorg/myimage --version ^1.0.0
# or this
crane ls myorg/myimage --version "<2.0.0,>1.0.0"
```

Would you open in accept such PR?

**Comment by tuananh** [comment]
@imjasonh what do you think?

**Comment by imjasonh** [comment]
I'm not opposed to it in theory. I tend to just pipe to `grep` for things like this myself, which gives me both a common language (regexp) instead of having to remember the syntax(es) for semver constraints.

One thing that would help make this a reality would be a simple, low-dependency library for parsing and matching semver constraints, since I definitely don't want to have to write one of those myself.

**Comment by tuananh** [comment]
> I'm not opposed to it in theory. I tend to just pipe to `grep` for things like this myself, which gives me both a common language (regexp) instead of having to remember the syntax(es) for semver constraints.
> 
> One thing that would help make this a reality would be a simple, low-dependency library for parsing and matching semver constraints, since I definitely don't want to have to write one of those myself.

I did that currently too but it's very limited due to the natural of semver.

if you're not opposed to it, I will work on a PR for this feature.
