### ISSUE TITLE
feat : add unit tests for list.go

### ISSUE THREAD

**Issue by khareyash05** [google/go-containerregistry#1670]
I would like to add unit tests for [link.go](https://github.com/google/go-containerregistry/blob/main/pkg/crane/list.go)

**Comment by imjasonh** [comment]
Are there any specific tests you had in mind? In general the code in `pkg/crane` is intended to be a little higher-level and user-friendly than the equivalent code in `pkg/v1/remote`, but since it's otherwise the same code we mostly just test `pkg/v1/remote`.

If there's meaningful code in `pkg/crane` that you think deserves tests please send a PR and we can discuss it!

Thanks!

**Comment by khareyash05** [comment]
Thank you! Since `pkg/v1/remote` is more used there is no need to add specific tests according to me.However I saw some files in `pkg/v1/remote` like `puller.go` and `pusher.go` which have missing test files. Would you like me to add tests to the files? @imjasonh

**Comment by imjasonh** [comment]
@jonjohnsonjr recently added these files (they're not yet released), so missing unit tests aren't a huge concern at the moment. If there's something you'd like to add tests for, though, please feel free and cc @jonjohnsonjr on any PRs.

**Comment by jonjohnsonjr** [comment]
They're fairly well covered by https://github.com/google/go-containerregistry/pull/1672 which made all the other entrypoints go through `Pusher` and `Puller`, but we could probably use some tests that explicitly exercise pusher and puller.
