### ISSUE TITLE
crane: "invalid tar header" 

### ISSUE THREAD

**Issue by chyashi** [google/go-containerregistry#1838]
### Describe the bug
I am encountering an "invalid tar header" error when attempting to push a valid Docker image tarball to a container registry using Crane. The source tarball is confirmed to be valid and follows the Docker image archive format, but the issue persists. I have reviewed the code, configuration, and environment without resolution, indicating a potential problem with how Crane is handling the tarball. 

### Additional context

- Output of `crane version`
- Registry used (e.g., GCR, ECR, Quay)

**Comment by a-h** [comment]
Without an example of the valid Docker image tarball that's getting the error, I don't see how this could be investigated by anyone else. Have you got a minimal example?

I ran into the same error message, but for a gzipped image. `docker load` happily loads a gzipped image, but crane requires the tar format. I was wondering whether to do a PR to add support for gzipped output, since that's what's created by the Nix ecosystem's Docker tools.

**Comment by lrewega** [comment]
> I was wondering whether to do a PR to add support for gzipped output, since that's what's created by the Nix ecosystem's Docker tools.

I just ran into this precisely. Adding support for gzipped image tarballs would solve for at least one scenario that currently results in this error message.

**Comment by jidaojiuyou** [comment]
A similar problem：
https://stackoverflow.com/questions/40622162

in linux, i use crane pull command to pull a image to the *.tar file. then i use crane push command to push the tarball to registry and it is succeed.
but when i use windows to pull the image from registry, the containerd throw a exception:  archive/tar: invalid tar header: unknown
﻿
is the bug for crane push or crane pull  or the tarball file?
