### ISSUE TITLE
Best place to put new utility?

### ISSUE THREAD

**Issue by sharifelgamal** [google/go-containerregistry#188]
I'm working on adding a command to strip away timestamps from docker images to make them able to be built reproducibly, similar to the script we have [here](https://github.com/GoogleContainerTools/base-images-docker/blob/master/util/config_stripper.py) but in Go, and I was wondering where in the containerregistry this would fit best.

**Comment by jonjohnsonjr** [comment]
If it fits the model, put it under `v1/mutate`. Will you add it to `crane`? Or just as a library function?

**Comment by sharifelgamal** [comment]
It's going to accept either an Image object, or a Reader to the docker tarball and return an Image object. The plan was to add it to crane as well.

**Comment by jonjohnsonjr** [comment]
I'm not sure that this would be appropriate as a top-level `crane` command... I've been thinking about adding a `flatten` command, which is a similarly-niche thing.

WDYT about lumping a bunch of mutating operations under a `crane mutate` command?

`$ crane mutate flatten`
`$ crane mutate freeze` (I'm sure there's a much better name)

We might also want to throw `rebase` and `append` under there, too, though those feel a bit different because they're essentially metadata-only operations (they don't have to walk the whole filesystem like `flatten` and `freeze` would).

@ImJasonH any opinions here?

**Comment by ImJasonH** [comment]
I'd rather not bury all/most mutate methods under a subcommand, if we can avoid it. I don't have a problem with `crane flatten` or `crane freeze` (maybe `strip`?), as long as there's some real-world need for it (even first-party).

If there's a need for the library method and not the CLI surface, we can hold off on the latter until there's demand.

**Comment by sharifelgamal** [comment]
I'll stick to the library method for now, we have no pressing need for the CLI command yet.
