### ISSUE TITLE
Docker manifest schema 1 is not supported

### ISSUE THREAD

**Issue by josephndenton** [google/go-containerregistry#296]
This toolset seems unable to pull images that are stored with manifests using Docker's V2 schema 1 spec: https://docs.docker.com/registry/spec/manifest-v2-1/

```
go run cmd/crane/main.go pull iron/node:4.2.6 test.tar
2018/10/29 16:14:00 Pulling index.docker.io/iron/node:4.2.6
2018/10/29 16:14:02 writing image "test.tar": unsupported status code 404; body: 404 page not found
exit status 1
```

**Comment by mattmoor** [comment]
At this point "schema 1" is ancient, so I'm pretty sure this is a "won't fix".

This would require us to support a number of really ugly hacks (e.g. the signature handling) for a vanishingly small niche of images still in the "schema 1" format.

---
_On another note..._

Given that "schema 2" has been present since Docker 1.10, which predates their date-based version numbering (going back as far as 17.03), this means this image was _likely_ pushed 1-2 _**years**_ ago, and the likelihood of it containing an unpatched CVE is quite high.

**Comment by mattmoor** [comment]
This is however supported in the Python library: github.com/google/containerregistry
