### ISSUE TITLE
Caching support

### ISSUE THREAD

**Issue by Globegitter** [google/go-containerregistry#325]
I saw there was a PR https://github.com/google/go-containerregistry/pull/164 that tried to introduce caching, what is the status on this? It would be nice to get caching support as not just speed is a potential issue but also potentially cost when pulling from a private repo.

**Comment by jonjohnsonjr** [comment]
I think that was abandoned because it's hard to bolt onto the existing APIs without some more careful thought. We can likely pass it through as an immutable option in some cases, but ideally it would be general enough to work in multiple contexts and for multiple purposes -- somewhat transparently to the user.

Something similar landed in the python cousin of this project: https://github.com/google/containerregistry/pull/121

It would be even cooler if those were interoperable 😄 

I think it would help to have a mini design doc that spells out how this affects everything, but that takes a bit more time/effort than the prototype in #164

**Comment by ImJasonH** [comment]
Here's a strawman, based on recent discussion with @jonjohnsonjr 

```go
package cache

type Cache interface {
  Put(string, v1.Image) error
  Get(string) (v1.Image, error)
  Delete(string) error
}

// New returns an image wrapped the given caching implementation.
//
// Cache writes will be done lazily as inner image contents are consumed.
func Image(img v1.Image, c Cache) v1.Image {
  return &image{...}
}

// New FilesystemCache returns a Cache implementation backed
// by writing files to a local filesystem.
func NewFilesystemCache(path string) Cache {
  return &fscache{...}
}

// TODO: NewInMemoryCache, etc.
```

This can be composed with `remote.Image` and `remote.Write` (or `daemon.Write`, `tarball.Write`, etc.) to populate a cache:

```go
rimg, _ := remote.Image(ref1, ...)
cimg := cache.Image(rimg, cache.NewFilesystemCache("/cache"))
_ = remote.Write(ref2, cimg, ...)
```

This would pull only layers not found in the local cache, and, when layers are consumed during `Write`, will populate the local cache.

The the cache-aware `LayerByDigest` method can first check the cache, then fallback to the inner `Image`'s implementation, and populate the cache as that layer is read. Since images are already lazily consumed everywhere already, this should just plug in to everything nicely.

-----

@jonjohnsonjr also wants a read-only cache implementation, which could be achieved with a `cache.ReadOnly(c)` method that takes a `Cache` and returns a read-only version of it (`Put` and `Delete` are no-ops):

```go
cimg := cache.Image(rimg, cache.ReadOnly(cache.NewFilesystemCache("/cache")))
```

-----

Open Questions:
* Should `cache.Image` fail if the image it's given is itself a `&cache.image{}`? Or should this be allowed, as a way to write to two different caches (for some reason)
* Can (should?) we make the cache format interoperable with the Python containerregistry client?
* Do we want an explicit `cache.Image` method that reads an image from the local cache (failing if it isn't found) and `cache.Write` method that populates the cache?
* We should have tests that this all plays nicely with `mutate` and `stream` especially, those are always the hard ones.

cc @yiranwang52 and @codygibb let me know if you think this would work for you, or if I missed anything.

**Comment by jonjohnsonjr** [comment]
What do you think about caching `Layer.Uncompressed` as well?

**Comment by ImJasonH** [comment]
Sure, that should be pretty easy. If this approach looks good to you I can work on that.

**Comment by yiranwang52** [comment]
Yes this would work for us.
Minor comment: you might not need delete() in the interface? since there could be implementations like a LRU cache that handles deletion itself

**Comment by ImJasonH** [comment]
@yiranwang52 Good point. I'm definitely a fan of keeping the interface as minimal as possible, but I think even an implementation that automatically deletes not-recently-used layers would benefit from having some way to explicitly evict layers. Or an implementation could just not support it and return a not-implemented error.

I'd love to include an LRU in the library's own filesystem cache implementation, since that way others can share it. I'm imagining functional options for `NewFilesystemCache` that let callers specify the max cache size (`WithMaxTotalSize(bytes int64)`?), and to cover the Kaniko use case, an option to ignore cached layers older than X (`WithMaxAge(age time.Duration)`) -- but not to explicitly delete layers that are found to be too old.

I think #458 is looking good, and we can add these options later. If you (or anyone reading this) is interested in adding more options for the fs cache, that'd be great.

**Comment by ImJasonH** [comment]
NB: The implementation in #458 also doesn't play nicely with `stream.Layer` (yet?), because the `stream.Layer` doesn't know its own digest/diffID to be able to look up in the cache. We could make cache impls aware to skip cache lookups for stream layers; as of that PR, they just fail with "I haven't figured out my digest yet 🤷‍♂ "

To support `stream.Layer`, the fs cache impl could do something like write streamed layer contents to some temp file, then after it's done and it knows the digest, move it to the correct location in the cache directory.

A `stream.Layer` would still not be able to take advantage of the cache, since it won't know its own digest the next time it's used, but at least we can populate the cache in case a later non-`stream.Layer` has the same contents.

I'm not convinced it's worth caring about just yet, since I don't know if anybody actually uses `stream.Layer` in practice, and we can just document that caching doesn't work with streaming, for somewhat obvious reasons.
