### ISSUE TITLE
Upload layer loses authentication on PATCH

### ISSUE THREAD

**Issue by lw346** [google/go-containerregistry#472]
Set up:
 * Docker V2 registry with bearer token authentication required
 * Uploading an image via kaniko - revision 8621d738a07bc74b2adeafd175a3c738423577a0

What is happening:
 1. Ping sent to `https://registry.example.com/v2/`
    - Response with 401 directing to `registry-auth.example.com`
 1. Request made to `registry-auth.example.com` with appropriate scope
    - Response with 200 providing `<token>` in the JSON response body
 1. POST request made to `https://registry.example.com/v2/test-image/blobs/uploads/`
    - Request contains Authentication header set to `Bearer <token>`
    - Response is 202 Accepted with Location set to `https://registry.example.com/v2/test-image/blobs/uploads/some-hash`
 1. PATCH request made to `https://registry.example.com/v2/test-image/blobs/uploads/some-hash`
    - Request does not contain any Authentication header
    - Response is 401 directing to `registry-auth.example.com`
 1. Upload attempt terminates with error

What I expect to happen:
 * PATCH request in step 4 should contain Authentication header set to Bearer token

**Comment by jonjohnsonjr** [comment]
Are you certain that the host for steps 4 and 5 are both `registry.example.com`? Is step 4 being redirected to another host?

**Comment by lw346** [comment]
After taking a packet capture, it's the same host, but a different scheme - ie. calling POST on `https://registry.example.com` redirects to `http://registry.example.com`.

I'm happy to take this as user error, but it was still a bit confusing to debug.

**Comment by jonjohnsonjr** [comment]
> https://registry.example.com redirects to http://registry.example.com

Looks like dropping the Authorization head in this case is the [golang http client](https://golang.org/pkg/net/http/#Client), which seems to be the right thing to do from a security perspective.

> registry.example.com:443

Ah. [This check](https://github.com/google/go-containerregistry/blob/ca8b66cb1b793f7fb0e3c191ad9a37eb3dc80ea0/pkg/v1/remote/transport/bearer.go#L56-L61) is probably failure because of that port. We could use [`net.SplitHostPort`](https://golang.org/pkg/net/#SplitHostPort) (or something else) to normalize the host when we match that...
