### ISSUE TITLE
Support for authenticating with GCR using JSON Key (Service Account)

### ISSUE THREAD

**Issue by mofirouz** [google/go-containerregistry#482]
I'm using go-containerregistry as a library in my application to interact with DockerHub, GCR, ECR and other private Docker registries. This application does not run within a Kubernetes environment so I cannot default to credentials available in a Kubernetes / GKE environment to authenticate with Google/GCR. 

I'd like to authenticate by passing in a Service Account in JSON file format to an `authn` provider (as described here: https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file). 

From the documentation above, it looks like the username should be set to `_json_key` while the password is the content of the JSON file (either plain or base64 encoded). However doing so will cause the following error with message `<empty transport.Error response>`.

Is authenticating using a service account supported? If so, how should I go about it? 

Any help is highly appreciated.

**Comment by mofirouz** [comment]
To add more context and code examples:

```go
serviceAccount := `{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "...",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "..."
}`

creds := &authn.Basic{
  Username: "_json_key",
  Password: serviceAccount,
}

repoName := "repo/name"

repo, err := name.NewRepository(repoName)
if err != nil {
  println(err.Error())
  return err
}

tags, err := remote.List(repo, remote.WithAuth(creds))
if err != nil {
  println(err.Error())
  return nil, err
}
```

**Comment by mofirouz** [comment]
Ignore this issue - I fixed it by prefixing repoName with `us.gcr.io` (🤦‍♂) - At least this remains here for the next poor soul!

Thanks a lot for this awesome repo!

**Comment by jonjohnsonjr** [comment]
To add a bit of explanation for the next poor soul:

What's happening here is that `name.NewRepository("repo/name")` is defaulting the registry to dockerhub, so requests are going to `"https://index.docker.io/v2/repo/name/tags/list"` instead of `"https://us.gcr.io/v2/repo/name/tags/list"`. 

You can make sure this doesn't happen by enforcing strict validation while parsing (no defaulting):
```go
repo, err := name.NewRepository("repo/name", name.StrictValidation)
```

which will fail with `strict validation requires the registry to be explicitly defined`.

<hr>

PS: Docker is a pretty reputable company, but you've just leaked that private key to them, so you might want to rotate it 😅 . If you're feeling ambitious and don't want to send your private key over the network, you could probably use [this](https://godoc.org/golang.org/x/oauth2/google#JWTAccessTokenSourceFromJSON) to produce access tokens, then construct your own authenticator (I've done something similar [here](https://github.com/google/go-containerregistry/blob/e8c6a4993fa7c12b6ca56007739116b27ecb84c1/pkg/v1/google/auth.go#L80-L93)).

PRs are welcome if you're interested in adding something like
```go
func NewJSONKeyAuthenticator(jsonKey []byte) (authn.Authenticator, error)
```
to `pkg/v1/google`, since you're probably not the only person who is interested in doing that 😃.

**Comment by mofirouz** [comment]
Oh this is awesome! Thanks so much. I'll take a look and will try and open a PR.
