### ISSUE TITLE
Preserve tag when writing to a tagged and digested image reference

### ISSUE THREAD

**Issue by glyn** [google/go-containerregistry#540]
Currently the tag is discarded. For example:
```
$ crane copy glyn/cranetest:1@sha256:c1224bb80cf7ce69efe55c438bbbd0ac7d73ab0bcb8548dabc402e3b791cbacc glyn/cranetestcopy:1@sha256:c1224bb80cf7ce69efe55c438bbbd0ac7d73ab0bcb8548dabc402e3b791cbacc
$ docker pull glyn/cranetestcopy:1
Error response from daemon: manifest for glyn/cranetestcopy:1 not found: manifest unknown: manifest unknown
```

Since ggcr preserves repo digests, the digest can safely be discarded when both tag and digest are provided in the target image reference.

Without this, at least one downstream consumer is having to add [support for this feature](https://github.com/pivotal/image-relocation/issues/33) and it would be better to make the semantics consistent.

**Comment by jonjohnsonjr** [comment]
So my interpretation [here](https://github.com/google/go-containerregistry/issues/351#issuecomment-459431865) was short-sighted. What is the _intent_ of `foo:tag@digest`? It seems like a comment when reading, but it's actually important when writing now. Great!

|                  | Read           | Write  |
| ------------- |:-------------:| :-----:|
| foo:tag      | tag | tag |
| foo@digest      | digest      |   digest |
| foo:tag@digest | digest      |    tag |

We've already encoded some behavior in these types:
1. `name.Digest` - I care about security.
2. `name.Tag` -  Merkle _what?_

Tags are useful for documenting intent, so this is definitely something we should fix, but I'm wondering if we have to actually expose this to users.

Neither of the proposed PRs really jump out to me as being obviously the right thing to do. E.g. adding an API for `ParseWriteReference` is weird, since the code that uses the reference will know if it's reading or writing. Adding `WriteTarget` is a bit better, but again I'm really reluctant to increase the API surface if we can solve it another way.

This change is somewhat relevant: https://github.com/google/go-containerregistry/pull/532. Since we're preserving the original input, we can re-frame the user's input in a given context:

```go
if tag, err := name.NewTag(ref.String()); err == nil {
  ref = tag
}
```

I can think of two places we'd want to do this:
1.  [remote writes](https://github.com/google/go-containerregistry/blob/53e1ac5a7d185672cfa09b847b4fa32d229899d1/pkg/v1/remote/write.go#L369-L407), and
2. [tarball writes](https://github.com/google/go-containerregistry/blob/46a3528b82270ecea7c731c14e698ea24aa0bbca/pkg/crane/pull.go#L49-L64).

Are there any other scenarios?

I think I'd much rather see a slight behavior change, since there's an obvious opt-out to the change: if you don't want a tag to be written, *don't* use the `foo:tag@digest` form. Arguably, the fact that we're not already doing this is a bug.

**Comment by glyn** [comment]
I can't think of any other scenarios.

Unfortunately `name.NewTag(ref.String())` returns an error when `ref` has both a tag and a digest. I couldn't see any way to extract the tag without duplicating logic from the `name` package (not advisable IMO) or increasing the API surface.

https://github.com/google/go-containerregistry/pull/550 is another proposal which adds a functional option to allow the tag to be preferred over the digest. See what you think. (Probably needs some more unit tests of the new functional option in the cases where there isn't both a tag and a digest.)

**Comment by jonjohnsonjr** [comment]
> Unfortunately name.NewTag(ref.String()) returns an error when ref has both a tag and a digest. I couldn't see any way to extract the tag without duplicating logic from the name package (not advisable IMO) or increasing the API surface.

What do you think about stashing [this](https://github.com/google/go-containerregistry/blob/d341a7d90fa0aac2b61889e5b9ff163cdbafea8c/pkg/name/digest.go#L82-L85) away somewhere and exposing a method on `name.Digest` to access it? Something stupid like:

```go
func (d Digest) AsTag() (*Tag, bool) {
	return d.tag, d.tag != nil
}
```

Then in remote.Write* we can do something like:

```go
if d, ok := ref.(name.Digest); ok {
  if t, ok := ref.AsTag(); ok {
    ref = t
  }
}
```

It's pretty gross but I don't see a way to do this that I'm happy with, and adding a single method to Digest that returns something we're already parsing anyway seems like it might be the least gross thing to do... maybe... idk.

**Comment by glyn** [comment]
That seems a little obscure to me, but it's really your call and I'm more interested in this issue being addressed than in the precise nature of the code changes.

Was https://github.com/google/go-containerregistry/pull/550 gross too in your opinion? If so, why?

**Comment by jonjohnsonjr** [comment]
> Was #550 gross too in your opinion? If so, why?

I suspect most users would *always* want to use that option. It also imposes some changes on the caller rather than just fixing a bug. I'd prefer a solution that fixes the API between `name` and `remote` to something that changes the external API for callers... I think.

I'm leaning more towards https://github.com/google/go-containerregistry/pull/542 now -- maybe rename `WriteTarget` to just `Target`? That approach seems to best match reality.

In my head, this makes sense:

```go
	// Identifier accesses the type-specific portion of the reference used for reads.
        // For a reference containing both a tag and a digest, this will be the digest.
	Identifier() string

	// Identifier accesses the type-specific portion of the reference used for writes.
        // For a reference containing both a tag and a digest, this will be the tag.
	Target() string
```

What do you think?

**Comment by glyn** [comment]
Yes, something like that would work. Maybe those methods could each return a Reference?

(Please note I'm on vacation now until November 4th.)

**Comment by medyagh** [comment]
@jonjohnsonjr any cance we could have this feautre https://github.com/google/go-containerregistry/pull/703 ? 

in minikube this will speed up our start process and makes a meaninigful change for the users
