### ISSUE TITLE
Performance Metrics

### ISSUE THREAD

**Issue by pcj** [google/go-containerregistry#55]
How does this compare to https://github.com/google/containerregistry?

**Comment by jonjohnsonjr** [comment]
Any operations in particular that you're interested in?

**Comment by pcj** [comment]
Build and push

**Comment by jonjohnsonjr** [comment]
I'm currently too busy/lazy to do this myself, but I think a reasonable starting point (to get a rough idea) would be to benchmark [`ko`](https://github.com/google/go-containerregistry/tree/master/cmd/ko) against [`rules_k8s`](https://github.com/bazelbuild/rules_k8s), since `ko` is essentially a hyper-specialized golang-only form of `rules_k8s`.

In my personal use, I've found `ko` to be ~2x the speed of an equivalent `rules_k8s` setup -- likely due to golang's speedier (than python) gzip implementation and the fact that we can avoid some of the high fixed costs of bazel (e.g. jvm startup time). Again, I haven't done a ton of profiling, so my reasoning here is somewhat speculative.
