### ISSUE TITLE
How to configure credentials for GCR ?

### ISSUE THREAD

**Issue by jeunii** [google/go-containerregistry#593]
This is more of a question rather than an issue. I am going to use `crane` to pull images from upstream and then push to them to GCR. But Im not sure how to configure the credentials for GCR to use `crane`.

I am using Jenkins pipeline to clone the images. And the actual pipeline runs in k8s i.e. a docker image. Ive already got `crane` into the docker image. All I want to know is how to configure the GCR credentials. 

Currently I get
```
root@08f3f79b831e:/app/bin# ./crane cp ubuntu eu.gcr.io/<PROJECT>/ubuntu
2019/10/24 11:52:38 Pulling ubuntu
2019/10/24 11:52:38 No matching credentials were found, falling back on anonymous
2019/10/24 11:52:38 Pushing eu.gcr.io/<PROJECT>/ubuntu
2019/10/24 11:52:38 No matching credentials were found, falling back on anonymous
2019/10/24 11:52:39 failed to copy index: unsupported status code 404; body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v2/token</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by jonjohnsonjr** [comment]
There are a few ways to do this, depending on your environment. I'm not sure familiar with jenkins, but I'll do my best to help.

The simplest thing to do is populate the docker config file with some credentials. This is usually at `$HOME/.docker/config.json`, but you can override the location by setting `DOCKER_CONFIG` environment variable to a different directory.

In order to populate the config file, you'd need to provide some credentials. If you're running on GKE, it's possible that you can get credentials from the [metadata server](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications) (on a VM with [appropriate scopes](https://cloud.google.com/container-registry/docs/using-with-google-cloud-platform#access_scopes)). In fact, if you're running on GKE and pushing to GCR, I suggest you try using `gcrane` instead of `crane` for this, since it already knows how to get access tokens from the environment. If you're pushing to a GCR registry that it's in the same project as your cluster, everything should just work. If you're pushing to a different project, you'll need to make sure to grant access to the [GCE service account](https://cloud.google.com/container-registry/docs/using-with-google-cloud-platform#compute-engine).

If you're not using GKE, then you'll need to provide credentials through a kubernetes secret. There is a special type of secret, [`kubernetes.io/dockerconfigjson`](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials), that will populate the docker config file for you, but again you'll need to acquire some credentials first.

If you follow [these instructions](https://cloud.google.com/container-registry/docs/advanced-authentication#access_token) for logging in with an access token, be aware that those are short-lived and will expire, so you shouldn't use that method if you need long-lived credentials. Instead, you likely want to [create a service account and use its JSON key](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file) for your registry credentials. Per those instructions, you'll need to configure appropriate [access control](https://cloud.google.com/container-registry/docs/access-control) for that service account to be able to push to your project.

Hope that helps, let me know if anything is unclear.

**Comment by jeunii** [comment]
@jonjohnsonjr Thanks for your reply. Pretty informative.
I have once question though. I assume docker is NOT required to be installed right for this ? 
If there is no docker installed, does `gcrane` still expect files like `$HOME/.docker/config.json` to be present in the container ?

**Comment by jeunii** [comment]
ok so here is my problem. My GKE cluster and GCR repo are in the same repo. So technically, I should not need to provide any credentials. But I get the same error as in my original post.

Then just for the sake of it, I added the credentials that connect me to GCR. Since I use kaniko containers to build images, I used the very same JSON credentials file. So I know that one works.

First I mounted that file to `$HOME/.docker/config.json` and tried to run `gcrane cp ubuntu eu.gcr.io/<PROJECT>/ubuntu`. Same error.
Then I tried to mount the file and made it equal to the env variable `DOCKER_CONFIG` but still the same error :/ 
```
k exec -it default-j3d9k bash
jenkins@default-j3d9k:/home/jenkins/agent$
jenkins@default-j3d9k:/home/jenkins/agent$ cat /var/lib/jenkins/.docker/config.json
REDACTED
jenkins@default-j3d9k:/home/jenkins/agent$ gcrane copy docker.io/ubuntu:latest eu.gcr.io/<PROJECT>/ubuntu:latest
2019/10/25 00:59:33 Pulling docker.io/ubuntu:latest
2019/10/25 00:59:33 No matching credentials were found, falling back on anonymous
2019/10/25 00:59:34 Pushing eu.gcr.io/<PROJECT>/ubuntu:latest
2019/10/25 00:59:34 No matching credentials were found, falling back on anonymous
2019/10/25 00:59:34 failed to copy image: failed to copy index: unsupported status code 404; body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v2/token</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by jonjohnsonjr** [comment]
> I have once question though. I assume docker is NOT required to be installed right for this ?
If there is no docker installed, does gcrane still expect files like $HOME/.docker/config.json to be present in the container ?

Yep! We just read from the same config file. Docker doesn't need to be installed.

> ok so here is my problem. My GKE cluster and GCR repo are in the same project. So technically, I should not need to provide any credentials. But I get the same error as in my original post.

I'm really surprised by this. I'll try to see if I can repro.

> Then just for the sake of it, I added the credentials that connect me to GCR. Since I use kaniko containers to build images, I used the very same JSON credentials file. So I know that one works.

Are you using a credential helper for that? It would look something like...

```json
{
	"credHelpers": {
		"eu.gcr.io": "gcloud",
	}
}
```

or

```json
{
	"credHelpers": {
		"eu.gcr.io": "gcr",
	}
}
```

If so, you'd need to make sure the credential helper binary is also installed in the container via `gcloud auth configure-docker` or by installing https://github.com/GoogleCloudPlatform/docker-credential-gcr.

**Comment by jonjohnsonjr** [comment]
> I'm really surprised by this. I'll try to see if I can repro.

Oh man, this is my mistake. See https://github.com/google/go-containerregistry/pull/594

**Comment by jonjohnsonjr** [comment]
@jeunii if that change doesn't fix your problem, I'm happy to reopen this and help debug further.
