### ISSUE TITLE
Why is the log output being discarded?

### ISSUE THREAD

**Issue by kovkev** [google/go-containerregistry#596]
https://github.com/google/go-containerregistry/blob/f9947dc9e9f8a234eb279ce02b277dca184de9be/pkg/logs/logs.go#L25

**Comment by jromero** [comment]
If I understand it correctly it's disabled by default. These are global variables that you would set prior to executing any GGCR function to whatever logging config you'd like.

Example: 
```
logs.Warn = log.New(myWriter, "", log.LstdFlags)
```

**Comment by kovkev** [comment]
It's an odd way of configuring logging levels. There's no way to set the logging level using a flag, and we need to change the source code?

**Comment by jonjohnsonjr** [comment]
Yeah, this is a bit strange, but I think it's slightly better than the alternatives.

I wanted to avoid pulling in a huge dependency like logrus, so originally we just were using the standard [`log`](https://godoc.org/log) package. Unfortunately, that meant that we were polluting the logs of anyone that imported this library, see: https://github.com/google/go-containerregistry/issues/480

Since we had started out with a global logger, we couldn't really fix our API without breaking clients, so I came up with this. By default, we'll discard logs, so as not to annoy any dependents that don't care about them. I think this is the most polite thing to do, but I wanted to expose a way for dependents to re-enable those logs (the same way that we do).

For [crane and gcrane, we wire up `Warn` and `Progress`](https://github.com/google/go-containerregistry/blob/f9947dc9e9f8a234eb279ce02b277dca184de9be/cmd/crane/main.go#L25-L28) by default. I added a [`-v` flag](https://github.com/google/go-containerregistry/pull/582/files) to dump debug information.

> There's no way to set the logging level using a flag, and we need to change the source code?

I didn't want to add global flags to everything that imports this package, but I don't think it's too hard to wire up your own flags to these if needed.

I've been thinking about moving to https://github.com/go-logr/logr but I'm not sure if that's any better.

**Comment by jonjohnsonjr** [comment]
Closing this, feel free to reopen if you have more questions or a better idea.

**Comment by markusthoemmes** [comment]
I just ran into this as well. Should we revisit this design with `slog` being around now? Golang's default logging makes this difficult to integrate with structured logging componentry. I guess one could wrap a structured logger's `Warn` function into an io.Writer but... yuck.

We could make this backwards compatible by making the new slog global optional too and only write to it if set, otherwise write to the "old" globals.

Thoughts? Happy to pick that up if that sounds reasonable.
