### ISSUE TITLE
When token request is forbidden, the 403 is not propagated back to the client.

### ISSUE THREAD

**Issue by lindsayismith** [google/go-containerregistry#626]
Recently, the library has started to fall back to oauth to receive a token.  In the case where the original token request is forbidden due to permissions, it will then try the oauth method. If this fails, e.g. if the server doesn't support it, then the returned error does not include the forbidden info.

E.g. 1st request:
HTTP GET https://somewhere.docker.com/v2/token?scope=something&service=somewhere

Response: 403 Forbidden

Then, 2nd request:
HTTP POST https://somewhere.docker.com/v2/token

Response: 405 Method not allowed

The 405 is returned as the status code, not the 403.

**Comment by jonjohnsonjr** [comment]
This is the result of some combination of these two PRs:
https://github.com/google/go-containerregistry/pull/462
https://github.com/google/go-containerregistry/pull/566

The second PR was partially my attempt to fix someone using ACR, see here: https://github.com/bazelbuild/rules_docker/issues/1193#issuecomment-540186322

Looking back through that thread, it seems that they were actually using the IdentityToken the entire time (which signals that we should be using the oauth flow): https://github.com/bazelbuild/rules_docker/issues/1193#issuecomment-543387115

And my initial fix did actually work... #566 wasn't necessary at all.

I believe the actual bug was just their config file path being misconfigured for bazel: https://github.com/bazelbuild/rules_docker/issues/1193#issuecomment-543408534

I'll look into partially reverting #566 to avoid this behavior. If that breaks people, then we can go from there.
