### ISSUE TITLE
crane rebase : problems with environment variables

### ISSUE THREAD

**Issue by eddie71** [google/go-containerregistry#730]
I have two java images, one with 11.0.5 and one with 11.0.6. they are both based on the same template. For instance

FROM centos
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-11.0.5.10-0.el8_0.x86_64

RUN yum update -y  && \
    yum install -y csh && \
    yum install -y  rng-tools && \
    yum install -y hostname && \
    yum install -y wget && \
    yum install -y passwd && \
    yum install -y nc && \
    yum install -y expect && \
    yum install -y unzip && \
    echo "password" | passwd --stdin root

USER root
RUN yum install -y java-11-openjdk-devel-11.0.5.10-0.el8_0.x86_64
RUN rm -rf /tmp/*

ENV PATH $JAVA_HOME/bin:$PATH
CMD ["/bin/bash"]

Java 11.0.6 version
-----------------
FROM centos
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-11.0.6.10-0.el8_1.x86_64/

RUN yum update -y  && \
    yum install -y csh && \
    yum install -y  rng-tools && \
    yum install -y hostname && \
    yum install -y wget && \
    yum install -y passwd && \
    yum install -y nc && \
    yum install -y expect && \
    yum install -y unzip && \
    echo "password" | passwd --stdin root

USER root

RUN yum install -y java-11-openjdk-devel-11.0.6.10-0.el8_1.x86_64
RUN rm -rf /tmp/*

ENV PATH $JAVA_HOME/bin:$PATH
CMD ["/bin/bash"]

i created a simple app and extended 11.0.5
FROM java:11.0.5
ADD target/app-1.0-SNAPSHOT.jar /
CMD $JAVA_HOME/bin/java -cp /app-1.0-SNAPSHOT.jar com.test.Application

it works with 11.0.5 and if i build the image directly on 11.0.6, it works ok. It simply prints the java version and the value or JAVA_HOME

If i take the 11.0.5 and rebase it, i get the error
/usr/lib/jvm/java-11-openjdk-11.0.5.10-0.el8_0.x86_64/bin/java: No such file or directory
(its picking up the 11.0.5 env varaible still)

crane rebase --original edoey-docker-dev:5000/application:11.0.5 --rebased edoey-docker-dev:5000/application:11.0.6 --old_base edoey-docker-dev:5000/java:11.0.5 --new_base edoey-docker-dev:5000/java:11.0.6

Is this expected behavior? Cant rebasing not change environment variables set in a base layer?

**Comment by jonjohnsonjr** [comment]
> Is this expected behavior? Cant rebasing not change environment variables set in a base layer?

This is expected based on the current implementation. It would be interesting to be able to support something like this. Rebasing works at a layer level, which just contain the filesystem contents. Anything that modifies the [config file](https://github.com/opencontainers/image-spec/blob/master/config.md#properties) as an intermediate step is going to be hard to preserve.

The problem is that these modify the config file for your original image:
> ENV PATH $JAVA_HOME/bin:$PATH
> CMD ["/bin/bash"]

When we rebase it, we swap out that config file with the config file of the new base and replace the old layer info with the new base's layers. Unfortunately, the `ENV` directive isn't associated with a layer, it's just flattened into the original image's config file, so we don't really have a way to know that these `ENV` and `CMD`  modifications should be preserved (or an easy way to recognize them).

I think it's _possible_ to try to support something like this, but it would be some work. We could inspect the config files of both the `--original` image and the `--old_base`, diff them, and try to apply the diff to the `--new_base` config file, but I'm not sure if that's easy or generally safe to do. We'd probably also need to figure out different merge strategies for different data structures, e.g. do we just append environment variables to the list? What if there's a conflict with the new base?

cc @ImJasonH and @shimmerjs this seems fun
