### ISSUE TITLE
Don't use http.DefaultTransport in the CLI

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#77]
It has no timeouts.

See: https://github.com/golang/go/issues/24138 and https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

**Comment by dekkagaijin** [comment]
I'm planning on adding several nesting transports/clients that we've added to the python client (for good reasons). I can add a default timeout at the same time as that refactor.

**Comment by mattmoor** [comment]
FWIW, `http.DefaultTransport = foo` is a thing :)

**Comment by jonjohnsonjr** [comment]
> Given that the issue above doesn't get much attention

@adrcunha continuing here

I think that issue doesn't get much attention because for most people (at least for me), using `ko` is an interactive thing -- network flakes are easy to deal with by just re-running the command, so it's not really a big deal because at worst you've wasted a few seconds, and re-running benefits from the go build cache.

For the integration tests, a network flake means we have to teardown/recreate the entire universe and rebuild everything :(

If this really is an issue for y'all, we happily accept pull requests and bribes :wink: 

The would be to replace this with something simple that will retry low-level network errors once or twice: https://github.com/google/go-containerregistry/blob/d1e67cf25ac607e7cf7d49ee881647a28d0a0ce6/pkg/v1/remote/options.go#L39
