### ISSUE TITLE
Consider using docker/distribution/reference package vs. parsing things ourselves

### ISSUE THREAD

**Issue by dprotaso** [google/go-containerregistry#78]
We might want to internally use the package [github.com/docker/distribution/reference](https://github.com/docker/distribution/blob/master/reference)

I wouldn't want to expose these interfaces/structs to the consumers of this library.

**Comment by dekkagaijin** [comment]
Some discussion in the daemon implementation re: vendoring docker:
https://github.com/google/go-containerregistry/pull/53#issuecomment-378321208

I'd be less afraid of vendoring distribution, since "github.com/docker/distribution/digestset" and "github.com/opencontainers/go-digest" are both leaf nodes in the dependency graph.
