### ISSUE TITLE
update-codegen is broken

### ISSUE THREAD

**Issue by mattmoor** [google/go-containerregistry#782]
The new automation found this here: https://github.com/mattmoor/knobots-actions/runs/1226092559?check_suite_focus=true#step:6:135

```
	github.com/maxbrunsfeld/counterfeiter/v6@v6.2.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/code-generator@v0.19.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/maxbrunsfeld/counterfeiter/v6@v6.2.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
	k8s.io/code-generator@v0.17.2: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
```

**Comment by hasheddan** [comment]
From what I can tell so far, `update-codegen.sh` is pulling in a new version of `k8s.io/code-generator v0.19.2`, which then updates to `counterfeiter v6.2.3`, which breaks the vendored modules. Just running `go mod tidy`, `go mod vendor` works because we already require the `code-generator` version we want. However, there is a separate generation issue which needs to be fixed as well I believe. Looking into that now.
