### ISSUE TITLE
Invalid tar header

### ISSUE THREAD

**Issue by gvolpe** [google/go-containerregistry#783]
I have a valid tar file generated with Nix. It is in the format expected by the `docker load` command. Should this work with `crane` or what's the expected format?

```shell
> crane validate --tarball result
2020/10/09 18:02:44 failed to read image result: archive/tar: invalid tar header

> ls -al result 
lrwxrwxrwx 59 gvolpe  9 Oct 15:21 result -> /nix/store/gr6ilfb2f0v5yn6jfmy2all0xfp60dfr-custom-image.tar.gz
```

FWIW this works:

```shell
> docker load < result
Loaded image: custom-image:latest
```

**Comment by ImJasonH** [comment]
Would it be possible to attach the offending result tarball for analysis? A minimal repro would be especially helpful.

**Comment by gvolpe** [comment]
Sure, here is a minimal image that displays the same behavior, thanks for the quick reply! [nix-hello.tar.gz](https://github.com/google/go-containerregistry/files/5356279/nix-hello.tar.gz)

If it matters, it was generated with the following Nix file:

```nix
{ pkgs ? import <nixpkgs> { system = "x86_64-linux";} }:

pkgs.dockerTools.buildLayeredImage {
  name = "nix-hello";
  tag = "latest";
  contents = [ pkgs.hello ];
}
```

**Comment by gvolpe** [comment]
Hey @ImJasonH wondering if you got any chance to look into this? Or can you recommend any other tool that would allow me to push a Tarball Docker image to a registry? 

Much appreciated :bow:

**Comment by ImJasonH** [comment]
I wonder if the issue is that the tarball is gzipped? I get the same error message if I gzip a valid .tar file (`crane pull busybox busybox.tar && gzip busybox.tar > busybox.tar.gz`), then try to validate it (`crane validate --tarball busybox.tar.gz`).

`crane`, or the `pkg/v1/tarball` package more broadly, doesn't attempt to detect zipped tar files, except to see if _layers_ within the tar file are gzipped.

Unzipping your `nix-hello.tar.gz` and passing that to `crane validate` seems to work:

```
$ crane validate --tarball ~/Downloads/nix-hello.tar 
PASS: /Users/jasonhall/Downloads/nix-hello.tar
```

(Sorry it took so long to get back to you on this, on the bright side the solution seems to be pretty simple! 😄 )

**Comment by gvolpe** [comment]
@ImJasonH interesting, that seems easy enough! Let me try it out and I'll report back.

**Comment by gvolpe** [comment]
Can confirm it works, thanks a lot for the pointer! :tada:
