### ISSUE TITLE
Provide ability to update an image layout, ensuring all of its content is available

### ISSUE THREAD

**Issue by deitch** [google/go-containerregistry#813]
When using `v1/layout`, if I run `Path.AppendIndex()` / `Path.AppendImage()`, there is no way to say:

1. Update any missing blobs
1. Do not update the `index.json`, because there already is an entry

The `AppendIndex`/`AppendImage` already call `writeIndex`/`writeImage`, which sanely check each blob down the tree to see if it is there and, if not, then download it.

But the rest of `AppendIndex`/`AppendImage` creates the descriptor for use in `index.json` and then writes it. Most of the time this makes sense, but if the exact same descriptor already is there, it doesn't.

Practically, this means I can add a new image, or download all the missing blobs for an image and add it a second time, but I have no way to just download the missing blobs.

I see two ways to do this:

* make `writeIndex`/`writeImage` public, so someone can simply choose to call `WriteIndex` if they do not want to update `index.json`, or `AppendIndex` if they do
* make `AppendDescriptor` idempotent. If it is the _exact_ same descriptor, do not write it twice.

I am good with either of these, and happy to get a PR in if it will get reviewed and pulled.

Discussed offline with @jonjohnsonjr

**Comment by jonjohnsonjr** [comment]
Given the two options, I'd prefer just exposing `writeIndex` and `writeImage` because they seem generally useful and would solve this problem for you. While making `AppendDescriptor` idempotent sounds like a good idea, changing the existing behavior of `AppendDescriptor` might break something in ways that I didn't anticipate. If we want something like that, we can perhaps add another method, but if the first option unblocks you I'd say let's just go with that.

**Comment by deitch** [comment]
See #815
