### ISSUE TITLE
layout.RemoveDescriptor

### ISSUE THREAD

**Issue by deitch** [google/go-containerregistry#842]
Any objection to having a `layout.RemoveDescriptor()` function? We have lots of `Append*()`, but no way to remove something I don't want. 

Here is just one use case:

1. On Sunday I download an image `docker.io/foo/bar:latest` and save it via `AppendIndex()`, so it ends up with an entry in `index.json` using the official name annotation
1. On Monday the mutable tag latest is updated, so its root manifest is different'
1. On Tuesday I pull `docker.io/foo/bar:latest` and save it using the only tool I have `AppendIndex()`

I now have two entries in `index.json`, each pointing to a different root manifest.

I agree wholeheartedly that this is all because of mutable tags, which may very well be a blight upon technology, but they are there and used.

Either way, we probably should have a way to remove a descriptor from `index.json`.

I actually wouldn't mind a way to `RemoveImage()` which removes all of its children blobs, except for those in use by others. But that is a much heavier lift, and probably should be done in two steps:

1. Remove the reference in `index.json`
1. Do a "garbage collection" which removes anything that isn't part of a tree rooted in `index.json`

But the latter could have negative side-effects, so I would defer on those for now.

**Comment by jonjohnsonjr** [comment]
Good morning 🍵 

I don't have specific guidance, but I'll brain dump anything that feels relevant:

> no way to remove something I don't want

We definitely need something like this, but I'd like to think through the API first for naming purposes so we can be consistent (even if we don't implement all of it at once). (Ideally, we could also be naming consistent across packages, but that's a tall order.)

Just guessing we'll end up with...

```go
// Remove from index.json only.
func (l *Path) RemoveDescriptor(???) error

// Remove from index.json and GC any blobs (including manifests) referenced by the image
// that are no longer reachable from index.json.
func (l *Path) RemoveImage(???) error

// Remove from index.json and GC any blobs (including manifests) referenced by the index
// that are no longer reachable from index.json.
func (l *Path) RemoveIndex(???) error

// Remove just the blob, don't do any GCing.
// Document that if you referenced a blob from index.json you'll need to call RemoveDescriptor.
// (Perhaps we should have another method that does both? Maybe call this "DeleteBlob"?)
func (l *Path) RemoveBlob(h v1.Hash) error

// Delete any blobs (including manifests) that are no longer reachable from index.json.
func (l *Path) GarbageCollect() error
```

> But the latter could have negative side-effects, so I would defer on those for now.

Exactly. For `RemoveIndex` and `RemoveImage`, we can't just cheat and call `l.GarbageCollect()` because we might GC things that weren't orphaned by the artifact we're removing. Since we exposed `WriteBlob` and `WriteFile`, we committed to allowing callers to add files that aren't actually referenced by anything, and we don't want to stomp on their toes. We also might not need both of these methods if we choose appropriate method parameters.

What would `RemoveDescriptor` look like? Delete by index (seems racey unless we're clever)? Delete by digest? Delete by `match.Matcher`? Do we just delete the first descriptor we come across or all of them? Should we return the `[]v1.Descriptor`s that we deleted?

<hr>

One nice thing about the current API being append-only is that we don't have to worry as much about concurrent access, but we should probably think about it.

We should be able to have multiple goroutines interact with a `layout.Path` instance safely. Ideally, we could also have multiple `layout.Path` instances operating on the underlying directory safely, but that would involve some filesystem locking (or merkledag cleverness), and I don't have much experience doing that in a cross-platform go-idiomatic way. I think containerd probably has to deal with similar issues, so maybe we could ~~steal~~ be inspired by their implementation, but I'm guessing it's easier because they can coordinate everything through the daemon process.

Garbage collection is hard... I'm fine with adding a specific method to `layout.Path` to do this, but it would be nice to think about how that would compose with a generic traversal function (or if we can extract it). (`remote.MultiWrite` needs to do something similar.) We can just do stop the world GC for now (either filesystem locking or within `layout.Path` or both, whichever you are willing to implement), but it would be cool to get clever about it.

We might want to start maintaining an in-memory adjacency list to speed this up (perhaps optionally to avoid OOM for enormous layouts...) something like:

```go
// What blobs does the key reference?
out map[string][]string

// What blobs reference the key?
in map[string][]string
```

My first thought was to use `v1.Hash` for the keys and values, but if we use `string` we can also include `index.json` in the domain 😄. We could also make these values `v1.Descriptor`s if we wanted to use these data structures for more than just ref counting.

<hr>

My brain is still kind of coming onlidne, but one "clever" strand of thread we could pull on is something like:

```go
func (l Path) RemoveDescriptor(???) (Path, error)
```

This would return a new `layout.Path` with the descriptor (or whatever) removed, leaving the original one intact. This follows the functional/immutable style of API that we use everywhere. For the actual underlying implementation, we could actually do a full copy, or do some symlink cleverness, or maintain multiple `index.json` files in the same directory (perhaps the original `index.json` becomes `index.$(sha256sum index.json).json` or something).

In fact, this is probably how we should have implemented the `layout` package altogether. The `mutate` package should have a set of functions to mutate an index instead of these being methods on the `layout.Path`. I think at the time of implementation, `mutate` only operated on images, and I was thinking more about how to efficient implement this instead of how it would compose with other packages. If you're up to the challenge, we should think about how we can pull some or all of this logic into `mutate`. Callers should be able to do any of this stuff to arbitrary indexes, not just `layout.Path`.

This does change the model a bit from "directly do this mutable operation to a layout" to "abstractly perform this mutation and then we will later serialize it by writing back to the original layout", which makes some things harder to reason about but other things much nicer... still, it doesn't solve the problem of GC unless you write to a different layout and delete the original. I have more thoughts about that but my battery is about to die 😄 

<hr>

> I agree wholeheartedly that this is all because of mutable tags, which may very well be a blight upon technology, but they are there and used.

FWIW, you can currently achieve this effect by constructing an `ImageIndex` with that descriptor removed (cumbersome but possible with `mutate`) and then calling `layout.Write`. It wouldn't be as efficient, but it _would_ ensure all the invariants we expect, and it might be good enough for now? Similarly, you could just overwrite the `index.json` by calling `path.WriteFile`. For the one use case you propose, we could also expose a way to iterate over the `index.json` in reverse so that you read the "most recent" tag (or just `FindManifests(tag)[-1]`).

All of these approaches still leave blobs around you don't need, but maybe that's fine for now?

**Comment by deitch** [comment]
> Just guessing we'll end up with...

I like that, it seems clean.

> What would RemoveDescriptor look like? Delete by index (seems racey unless we're clever)? Delete by digest? Delete by match.Matcher? 

I originally thought about by digest, but I think by Matcher is better, since it includes digest (and we can add a `match.Digest` option. Actually, I will add it right now.)

> Do we just delete the first descriptor we come across or all of them? 

All of them. 

> Should we return the []v1.Descriptors that we deleted?

I think that is a nice thing to do.

> we can't just cheat and call l.GarbageCollect() because we might GC things that weren't orphaned by the artifact we're removing. Since we exposed WriteBlob and WriteFile, we committed to allowing callers to add files that aren't actually referenced by anything, and we don't want to stomp on their toes. We also might not need both of these methods if we choose appropriate method parameters.

Drat. I didn't think about that. FWIW, containerd solves this by requiring everything to have either a root pointed to by an image tag, or by having a special GC label that points to a blob. We have the "image" tag pointer (root of the tree in `index.json`), but we don't have that since there are no labels/tags defined in the spec.

I don't have a clean answer to this. 

I am thinking we should build this up in stages. I would offer the following:

```go
// Remove from index.json only.
func (l *Path) RemoveDescriptor(matcher match.Matcher) error

// RemoveBlob explicitly
func (l *Path) RemoveBlob(h v1.Hash...) error

// Delete any blobs (including manifests) that are no longer reachable from index.json.
// This can delete blobs that you pulled down manually
func (l *Path) GarbageCollect() error

// report anything that would be garbage collected because it has no reference
func (l *Path) GarbageReport() []Digest
```

This isn't perfect by any stretch, but does things that can be built upon:

* remove a descriptor using a Matcher
* remove one or more blobs
* garbage collect; yes, this might remove something that was written explicitly, but `GarbageReport()`  gives one the option to see what it would do

**Comment by deitch** [comment]
> We should be able to have multiple goroutines interact with a layout.Path instance safely. Ideally, we could also have multiple layout.Path instances operating on the underlying directory safely, but that would involve some filesystem locking (or merkledag cleverness), and I don't have much experience doing that in a cross-platform go-idiomatic way. I think containerd probably has to deal with similar issues, so maybe we could steal be inspired by their implementation, but I'm guessing it's easier because they can coordinate everything through the daemon process.

Yeah, but containerd controls access via a single owning daemon. We don't have that. It might not just be 2 goroutines; it might be 2 independent processes. I don't see any option here.

> My first thought was to use v1.Hash for the keys and values, but if we use string we can also include index.json in the domain 😄. We could also make these values v1.Descriptors if we wanted to use these data structures for more than just ref counting.

Now my head hurts. How do you keep track of all of these at once?

> This would return a new layout.Path with the descriptor (or whatever) removed, leaving the original one intact. This follows the functional/immutable style of API that we use everywhere. For the actual underlying implementation, we could actually do a full copy, or do some symlink cleverness, or maintain multiple index.json files in the same directory (perhaps the original index.json becomes index.$(sha256sum index.json).json or something).

This concerns me. The spec doesn't support (but doesn't reject, either) multiple `index.json` in a single dir. I don't know that people will know what to do with it, and we will end up rapidly with a proliferation of `index.json`.

I can see it as an option, but as a default? I think `index.json` is like a database; single copy.

**Comment by deitch** [comment]
> I originally thought about by digest, but I think by Matcher is better, since it includes digest (and we can add a match.Digest option. Actually, I will add it right now.)

Done. Updated #841 to include it. Once that is in, you could remove by digest by doing:

```go
p.RemoveDescriptor(match.Digest(hash))
```

**Comment by deitch** [comment]
> FWIW, you can currently achieve this effect by constructing an ImageIndex with that descriptor removed (cumbersome but possible with mutate) and then calling layout.Write. It wouldn't be as efficient, but it would ensure all the invariants we expect, and it might be good enough for now? 

How do I do that? [v1.ImageIndex()](https://godoc.org/github.com/google/go-containerregistry/pkg/v1#ImageIndex) is an interface that lets me retrieve information from the `ImageIndex` but does not appear to allow me to mutate it? Same for [mutate](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/mutate) which appears to let me construct a new `ImageIndex` by appending to an existing one, but doesn't seem to have any way to mutate an existing one.

I actually tried to put together a PR with `layout.ReplaceDescriptor`/`ReplaceIndex`/`ReplaceImage`, and it was fairly straightforward... until I hit the "how do I mutate the index?" issue.

**Comment by jonjohnsonjr** [comment]
> but doesn't seem to have any way to mutate an existing one.

Right -- we want these things accessor interfaces to be immutable for a variety of questionable philosophical reasons, but to "mutate" one:

```go
path, _ := layout.FromPath(p)
ii, _ := path.ImageIndex()
mutated :=  constructNewImageIndexWithDescriptorRemoved(ii)
path, _ = layout.Write(p, mutated)
```

That will just overwrite what was already there. It would be more a bit more efficient to just call `path.WriteFile("index.json", ...)`, since we're just removing a descriptor and don't have to write any new blobs.

**Comment by deitch** [comment]
OK, take a look at #848 @jonjohnsonjr and see if that fits the bill. We can add tests if we are on the right track.

**Comment by deitch** [comment]
> Ideally, we could also have multiple layout.Path instances operating on the underlying directory safely, but that would involve some filesystem locking (or merkledag cleverness), and I don't have much experience doing that in a cross-platform go-idiomatic way. I think containerd probably has to deal with similar issues, so maybe we could steal be inspired by their implementation, but I'm guessing it's easier because they can coordinate everything through the daemon process.

I am going to open a new issue dedicated to this. I think it deserves its own (and if you disagree, you always can close it).
