### ISSUE TITLE
Docker version upgrade?

### ISSUE THREAD

**Issue by natalieparellano** [google/go-containerregistry#916]
Is there any plan to upgrade the version of docker used by this project? It's currently at `github.com/docker/docker v1.4.2-0.20190924003213-a8608b5b67c7`, which is a bit old.

For context, our project imports GGCR and tries to stay on the same version of docker to avoid dependency pain (https://github.com/buildpacks/imgutil/issues/70) however this is now causing us new pain (https://github.com/buildpacks/lifecycle/issues/504).

**Comment by jonjohnsonjr** [comment]
For a little bit of context, I had a bit of an adventure carving out a slice of the docker dependency graph that _didn't_ pull in the entirety of docker/docker. I'm hesitant to update anything without careful consideration.

E.g. I'd like to avoid just pulling in github.com/containerd/containerd/platforms because of https://github.com/containerd/containerd/blob/66fec3bbbf91520a1433faa16e99e5a314a61902/platforms/cpuinfo.go#L33

**Comment by jonjohnsonjr** [comment]
This commit is a problem, IMO. We could update to something before that or try to fix it upstream.

https://github.com/moby/moby/commit/7a9cb29fb980c0ab3928272cdc24c7089b2fcf64

**Comment by josegonzalez** [comment]
@jonjohnsonjr looks like the upstream change to remove that init call was merged, but not sure if the fix makes it easier to upgrade here now...

**Comment by jonjohnsonjr** [comment]
I'm not sure either. Whenever I think I understand go modules, I quickly learn that I don't.

Can we pin our containerd dep to what @ImJasonH merged and update the docker dep to whatever y'all need? What versions of docker/docker are acceptable for buildpacks folks?

**Comment by jromero** [comment]
FWIW, `pack` successfully updated to `v20.10.0-beta` via https://github.com/buildpacks/pack/pull/960. I would assume `v20.10.0` would be acceptable. Plus, it's pre-`v20.10.2`, in order to omit the problematic commit mentioned by @jonjohnsonjr.

**Comment by jonjohnsonjr** [comment]
That's agreeable to me, if you want to send a PR.
