### ISSUE TITLE
Perform insecure ping fallback concurrently

### ISSUE THREAD

**Issue by jonjohnsonjr** [google/go-containerregistry#991]
We currently try https then http when pinging the registry: https://github.com/google/go-containerregistry/pull/360

This introduces long delays: https://github.com/google/go-containerregistry/pull/715

We could do both concurrently to avoid the delays.

**Comment by pangsq** [comment]
If we do ping concurrently with both schemes, the final scheme in transport will be random (depends on which request is achieved quickly) or another delay is introduced (if we choose to wait both requests are answered or timeout and determine which scheme is better).
I think the `reLocal` in https://github.com/google/go-containerregistry/issues/279 is meaningless for most people and should not be used at default and we don't need to try `https` if the registry is `insecure` because we config it.

**Comment by pangsq** [comment]
#1002  I created a PR which is related with this issue.

**Comment by jonjohnsonjr** [comment]
Fixed in https://github.com/google/go-containerregistry/pull/1521
